Repository YeaHubTeam/yeahub-platform, pull requests merged in 2025-10, with the labels that each got.

#903 YH-1378: added tabs for resources and requests
  public/locales/en/resources.json
  public/locales/ru/resources.json
  src/app/providers/router/config/routeConfig.tsx
  src/app/providers/store/config/config.ts
  src/pages/admin/ResourcesPage/index.ts
  src/pages/admin/ResourcesPage/model/hooks/useGetResourcesPageTabs.tsx
  src/pages/admin/ResourcesPage/model/selectors/resourcesAllTabSelectors.ts
  src/pages/admin/ResourcesPage/model/selectors/resourcesRequestsTabSelectors.ts
  src/pages/admin/ResourcesPage/model/slice/resourcesAllTabSlice.ts
  src/pages/admin/ResourcesPage/model/slice/resourcesRequestsTabSlice.ts
  src/pages/admin/ResourcesPage/model/types/resourcesAllTabTypes.ts
  src/pages/admin/ResourcesPage/model/types/resourcesRequestsTabTypes.ts
  src/pages/admin/ResourcesPage/ui/ResourcesPage.lazy.tsx
  src/pages/admin/ResourcesPage/ui/ResourcesPage.tsx
  src/pages/admin/ResourcesPage/ui/tabs/ResourcesAllTab/ResourcesAllTab/ResourcesAllTab.module.css
  src/pages/admin/ResourcesPage/ui/tabs/ResourcesAllTab/ResourcesAllTab/ResourcesAllTab.skeleton.tsx
  src/pages/admin/ResourcesPage/ui/tabs/ResourcesAllTab/ResourcesAllTab/ResourcesAllTab.tsx
  src/pages/admin/ResourcesPage/ui/tabs/ResourcesAllTab/ResourcesAllTabPagination/ResourcesAllTabPagination.module.css
  src/pages/admin/ResourcesPage/ui/tabs/ResourcesAllTab/ResourcesAllTabPagination/ResourcesAllTabPagination.tsx
  src/pages/admin/ResourcesPage/ui/tabs/ResourcesRequestsTab/ResourcesRequestsTab/ResourcesRequestsTab.module.css
  src/pages/admin/ResourcesPage/ui/tabs/ResourcesRequestsTab/ResourcesRequestsTab/ResourcesRequestsTab.tsx
  src/pages/admin/ResourcesPage/ui/tabs/ResourcesRequestsTab/ResourcesRequestsTabPagination/ResourcesRequestsTabPagination.module.css
  src/pages/admin/ResourcesPage/ui/tabs/ResourcesRequestsTab/ResourcesRequestsTabPagination/ResourcesRequestsTabPagination.tsx
  src/pages/admin/ResourcesRequestsTablePage/index.ts
  src/pages/admin/ResourcesRequestsTablePage/model/selectors/resourcesRequestsTablePageSelectors.ts
  src/pages/admin/ResourcesTablePage/index.ts
  src/pages/admin/ResourcesTablePage/model/selectors/resourcesTablePageSelectors.ts
  src/pages/admin/ResourcesTablePage/ui/ResourcesTablePage/ResourcesTablePage.lazy.tsx
  src/shared/config/i18n/i18nTranslations.ts
  src/shared/config/store/State.ts
  src/shared/hooks/useQueryFilter.ts
Labels: feature, merge

#912 YH-1413: fix add image to resource
  src/entities/resource/model/types/resource.ts
  src/entities/resource/ui/ResourceCard/ResourceCard.tsx
  src/entities/resource/ui/ResourceForm/ResourceForm.tsx
  src/features/resources/createResource/model/lib/validation/resourceCreateSchema.ts
  src/features/resources/createResource/ui/ResourceCreateForm/ResourceCreateForm.tsx
  src/features/resources/createResourceRequest/model/lib/validation/resourceRequestCreateSchema.ts
  src/features/resources/createResourceRequest/model/types/resourceRequestCreateTypes.ts
  src/features/resources/createResourceRequest/ui/ResourceRequestCreateForm/ResourceRequestCreateForm.tsx
  src/features/resources/editResource/model/lib/validation/resourceEditSchema.ts
  src/features/resources/editResource/ui/ResourceEditForm/ResourceEditForm.tsx
  src/widgets/resources/ResourceBody/ui/ResourceBody.tsx
Labels: bug, merge

#914 YH-1385: Fix reset skills
  src/widgets/Marketplace/model/hooks/useMarketplaceFilters.ts
Labels: bug, merge

#893 Feature/YH-1345
  src/shared/ui/Table/Table.module.css
  src/shared/ui/Table/Table.tsx
  src/shared/ui/TableCellEntityList/TableCellEntityList.tsx
  src/widgets/CollectionsTable/ui/CollectionsTable.tsx
  src/widgets/CompaniesTable/ui/CompaniesTable.tsx
  src/widgets/QuestionsTable/ui/QuestionsTable.tsx
  src/widgets/SkillsTable/ui/SkillsTable.tsx
  src/widgets/SpecializationsTable/ui/SpecializationsTable.tsx
  src/widgets/UsersTable/ui/UsersTable.tsx
  src/widgets/resources/ResourcesTable/ui/ResourcesTable.tsx
Labels: feature, merge

#870 YH-1279: skeleton from media page
  src/app/layouts/LandingLayout/model/helper/SkeletonGenerator.tsx
  src/app/layouts/MainLayout/model/helper/SkeletonGenerator.tsx
  src/entities/guru/index.ts
  src/entities/guru/ui/GuruSocialsList/GuruSocialsList.module.css
  src/entities/guru/ui/GuruSocialsList/GuruSocialsList.skeleton.tsx
  src/entities/guru/ui/GurusItem/GurusItem.module.css
  src/entities/guru/ui/GurusItem/GurusItem.skeleton.tsx
  src/entities/guru/ui/GurusList/GurusList.skeleton.tsx
  src/entities/media/index.ts
  src/entities/media/ui/MediaLinkItem/MediaLinkItem.module.css
  src/entities/media/ui/MediaLinkItem/MediaLinkItem.skeleton.tsx
  src/entities/media/ui/MediaLinksList/MediaLinksList.skeleton.tsx
  src/pages/landing/MediaPage/index.ts
  src/pages/landing/MediaPage/ui/MediaPage.skeleton.tsx
  src/widgets/Landing/Media/index.ts
  src/widgets/Landing/Media/ui/AlarmFactBanner/AlarmFactBanner.module.css
  src/widgets/Landing/Media/ui/AlarmFactBanner/AlarmFactBanner.skeleton.tsx
  src/widgets/Landing/Media/ui/AlarmFactBanner/AlarmFactBanner.tsx
  src/widgets/Landing/Media/ui/GurusBlock/GurusBlock.skeleton.tsx
  src/widgets/Landing/Media/ui/OurMediaBanner/OurMediaBanner.module.css
  src/widgets/Landing/Media/ui/OurMediaBanner/OurMediaBanner.skeleton.tsx
  src/widgets/Landing/Media/ui/TelegramChannels/TelegramChannels.skeleton.tsx
Labels: feature, comments

#923 YH-1391: Fix translation bugs
  public/locales/en/profile.json
  public/locales/en/translation.json
  public/locales/ru/profile.json
  public/locales/ru/translation.json
  src/features/authentication/telegramLink/api/telegramLinkApi.ts
  src/shared/config/i18n/i18nTranslations.ts
Labels: review, feature

#922 YH-1386: Removed the specialization filter in ResourcesPage
  src/pages/wiki/ResourcesPage/ui/ResourcesPage.tsx
  src/widgets/Marketplace/ui/MarketplaceFiltersPanel/MarketplaceFiltersPanel.tsx
Labels: feature, merge
