Repository YeaHubTeam/yeahub-platform, pull requests merged in 2025-07, with the labels that each got.

#717 YH-11: fix link styles
  src/app/styles/normalize.css
Labels: bug, merge

#728 YH-1117: add Popover component with warning text for collection
  public/locales/en/collection.json
  public/locales/ru/collection.json
  src/entities/collection/index.ts
  src/entities/collection/ui/СollectionWarningInfo/CollectionWarningInfo.module.css
  src/entities/collection/ui/СollectionWarningInfo/CollectionWarningInfo.tsx
  src/shared/config/i18n/i18nTranslations.ts
  src/shared/ui/Card/Card.tsx
  src/shared/ui/Popover/index.ts
  src/widgets/Collection/ui/CollectionBody/CollectionBody.tsx
Labels: feature, merge

#721 YH-1060: filter list menu for author
  src/app/layouts/MainLayout/ui/MainLayout.tsx
  src/app/providers/router/config/routeConfig.tsx
  src/entities/auth/index.ts
  src/entities/auth/model/constants/authConstants.ts
  src/entities/auth/model/types/auth.ts
  src/widgets/Sidebar/model/types/sidebar.ts
Labels: feature, merge

#733 YH-1136: filling the landig, displaying text on mobile and correcting…
  src/widgets/Landing/BannerBlock/ui/AvatarGroup/AvatarGroup.module.css
  src/widgets/Landing/BannerBlock/ui/BannerImage/BannerImage.module.css
  src/widgets/Landing/BannerBlock/ui/BlockTitle/BlockTitle.module.css
Labels: bug, merge

#732 YH-1135: refactor premium subscribe component
  public/locales/en/subscription.json
  public/locales/ru/subscription.json
  src/app/providers/store/config/config.ts
  src/entities/subscription/api/subscriptionApi.ts
  src/entities/subscription/index.ts
  src/entities/subscription/model/selectors/subsrcriptionSelectors.tsx
  src/entities/subscription/model/slices/activeSubscriptionSlice.tsx
  src/entities/subscription/model/types/subscription.ts
  src/shared/config/i18n/i18nTranslations.ts
  src/shared/config/store/State.ts
  src/widgets/Profile/ui/SubscriptionTab/ui/PremiumSubscriptionTab/PremiumSubscriptionTab.tsx
  src/widgets/Profile/ui/SubscriptionTab/ui/SubscriptionTab/SubscriptionTab.tsx
Labels: feature, merge

#740 YH-1161: fix get and set active profile
  commitlint.config.ts
  config/jest/jest.polyfill.ts
  config/jest/jestFileMock.ts
  config/storybook/main.ts
  config/storybook/preview.ts
  config/storybook/webpack.config.ts
  config/webpack/types/types.ts
  config/webpack/webpackConfig.ts
  config/webpack/webpackDevServer.ts
  config/webpack/webpackLoaders.ts
  config/webpack/webpackOutput.ts
  config/webpack/webpackPlugins.ts
  config/webpack/webpackResolvers.ts
  postcss.config.ts
  src/entities/auth/api/__mocks__/data/authProfileQueryMockResponse.ts
  src/entities/auth/api/authApi.ts
  src/entities/auth/model/types/auth.ts
  src/entities/profile/model/selectors/profileSelectors.ts
  src/entities/resource/index.ts
  src/entities/user/api/userApi.ts
  src/features/profile/editProfileForm/helpers/editProfileFormHelpers.ts
  src/features/profile/editProfileForm/ui/EditProfileForm/EditProfileForm.tsx
  src/features/profile/editProfileForm/ui/PersonalInformationTabForm/PersonalInformationTabForm.tsx
  src/features/subscriptions/subscribe/ui/SubscribeButton/ui/SubscribeButton.tsx
  src/pages/landing/PublicMarketplacePage/ui/PublicMarketplacePage.tsx
  src/pages/profile/UserProfilePage/ui/UserProfilePage.tsx
  src/widgets/Header/ui/UserPreferencesHeader/UserPreferencesHeader.tsx
  src/widgets/Profile/ui/UserCard/ui/UserImageBlock/UserImageBlock.tsx
  src/widgets/Profile/ui/UserCard/ui/UserInfoBlock/UserInfoBlock.tsx
Labels: bug, merge

#746 YH-1190: fix incorrect link to settings page
  src/shared/constants/customRoutes.ts
  src/widgets/Collection/ui/CollectionBody/CollectionBody.tsx
  src/widgets/Header/ui/UserPreferences/UserPreferences.tsx
  src/widgets/interview/InterviewPreparation/ui/InterviewPreparation/InterviewPreparation.tsx
  src/widgets/interview/PassedQuizzesList/ui/PreviewPassedQuizzesList/PreviewPassedQuizzesList.tsx
  src/widgets/interview/QuestionsStatistic/ui/PreviewQuestionsStatistic/PreviewQuestionsStatistic.tsx
Labels: bug, merge

#741 YH-1157: Added a tooltip for the profile creation button
  public/locales/en/profile.json
  public/locales/ru/profile.json
  src/shared/config/i18n/i18nTranslations.ts
  src/shared/ui/Tooltip/Tooltip.tsx
  src/widgets/manageProfiles/ui/ManageProfilesPanel/ManageProfilesPanel.module.css
  src/widgets/manageProfiles/ui/ManageProfilesPanel/ManageProfilesPanel.tsx
Labels: feature, merge

#706 YH-1070: Added a tooltip. Replaced it with the desired text
  public/locales/en/questions.json
  public/locales/ru/questions.json
  src/features/quiz/learnQuestion/ui/LearnQuestionButton.tsx
  src/features/quiz/resetQuestionStudyProgress/ui/ResetQuestionStudyProgressButton.tsx
  src/shared/config/i18n/i18nTranslations.ts
Labels: feature, merge

#744 YH-1189: refactor tabs
  src/features/profile/editProfileForm/helpers/editProfileFormHelpers.ts
  src/features/profile/editProfileForm/ui/EditProfileForm/EditProfileForm.module.css
  src/features/profile/editProfileForm/ui/EditProfileForm/EditProfileForm.tsx
  src/pages/profile/SettingsProfilePage/ui/SettingsProfilePage.tsx
  src/shared/ui/Tabs/Tabs.module.css
  src/shared/ui/Tabs/Tabs.stories.tsx
  src/shared/ui/Tabs/Tabs.test.tsx
  src/shared/ui/Tabs/Tabs.tsx
  src/shared/ui/Tabs/hooks.ts
  src/shared/ui/Tabs/index.ts
Labels: review, feature

#745 fix/YH-1159
  src/features/profile/deleteProfile/ui/DeleteProfileButton/DeleteProfileButton.tsx
  src/shared/hooks/index.ts
  src/shared/hooks/useScreenSize.ts
  src/shared/hooks/useTruncation.ts
  src/shared/ui/Icon/Icon.tsx
  src/shared/ui/Modal/Modal.tsx
  src/shared/ui/Text/Text.module.css
  src/shared/ui/Text/Text.tsx
  src/shared/ui/Tooltip/Tooltip.module.css
  src/shared/ui/Tooltip/Tooltip.tsx
  src/widgets/manageProfiles/ui/ProfileCard/ProfileCard.module.css
  src/widgets/manageProfiles/ui/ProfileCard/ProfileCard.tsx
Labels: bug, merge

#754 YH-1163: fix input label and error label
  src/features/profile/changePassword/ui/ChangePassword.module.css
  src/features/profile/changePassword/ui/ChangePassword.tsx
Labels: bug, merge

#757 YH-1203: fixed the link to view statistics
  src/entities/subscription/ui/PremiumSubscriptionTooltipBody/PremiumSubscriptionTooltipBody.tsx
  src/entities/subscription/ui/SubscriptionCard/SubscriptionCard.tsx
  src/widgets/interview/QuestionsStatistic/ui/PreviewQuestionsStatistic/PreviewQuestionsStatistic.tsx
Labels: bug, comments

#759 YH-1198: limitation of features for the public trainer
  src/pages/landing/CreatePublicQuizPage/ui/CreatePublicQuizPage.tsx
Labels: feature, merge

#742 YH-1162: adding data retrieval, typing and adjustments
  src/app/msw/handlers.ts
  src/entities/payment/api/__mocks__/data/index.ts
  src/entities/payment/api/__mocks__/data/paymentsMock.ts
  src/entities/payment/api/__mocks__/index.ts
  src/entities/payment/api/__mocks__/paymentsListMock.ts
  src/entities/payment/api/paymentApi.ts
  src/entities/payment/index.ts
  src/entities/payment/model/constants/payments.ts
  src/entities/payment/model/types/payments.ts
  src/shared/config/api/apiTags.ts
  src/widgets/Profile/ui/SubscriptionTab/types/types.ts
  src/widgets/Profile/ui/SubscriptionTab/ui/PayHistoryItem/PayHistoryItem.tsx
  src/widgets/Profile/ui/SubscriptionTab/ui/PayHistoryList/PayHistoryList.tsx
  src/widgets/Profile/ui/SubscriptionTab/ui/PremiumSubscriptionTab/PremiumSubscriptionTab.tsx
  src/widgets/Profile/ui/SubscriptionTab/ui/SubscriptionPagination/SubscriptionPagination.tsx
Labels: feature, merge

#750 YH-1064: add access restriction for authors to work only with their own collections
  public/locales/en/translation.json
  public/locales/ru/translation.json
  src/entities/collection/model/types/collection.ts
  src/features/collections/deleteCollection/ui/deleteCollectionButton/DeleteCollectionButton.tsx
  src/features/collections/editCollection/ui/CollectionEditForm/CollectionEditForm.tsx
  src/pages/admin/CollectionPage/ui/CollectionPage.tsx
  src/pages/admin/CollectionsPage/ui/CollectionsPage/CollectionsPage.tsx
  src/shared/config/i18n/i18nTranslations.ts
  src/shared/types/types.ts
  src/shared/ui/Button/Button.module.css
  src/shared/ui/Checkbox/Checkbox.module.css
  src/shared/ui/Popover/PopoverMenu/PopoverMenu.tsx
  src/shared/ui/Popover/types.ts
  src/shared/ui/Table/Table.tsx
  src/shared/ui/Tooltip/Tooltip.module.css
  src/shared/ui/Tooltip/Tooltip.tsx
  src/shared/ui/Tooltip/types.ts
  src/widgets/CollectionsTable/ui/CollectionsTable.tsx
Labels: feature, merge

#762 YH-1206: fix left margin
  src/features/authentication/forgotPassword/ui/EmailSendModal/EmailSendModal.module.css
  src/features/authentication/forgotPassword/ui/EmailSendModal/EmailSendModal.tsx
  src/features/authentication/login/ui/LoginForm/LoginForm.module.css
  src/features/authentication/login/ui/LoginForm/LoginForm.tsx
  src/features/authentication/login/ui/RegistrationLabel/RegistrationLabel.tsx
  src/features/authentication/registration/ui/LoginLabel/LoginLabel.tsx
  src/features/authentication/registration/ui/RegisterForm/RegisterForm.module.css
  src/features/authentication/registration/ui/RegisterForm/RegisterForm.tsx
  src/features/authentication/socialAuthenticate/SocialAuthenticateList/ui/SocialAuthenticateList.module.css
  src/features/authentication/socialAuthenticate/SocialAuthenticateList/ui/SocialAuthenticateList.tsx
Labels: bug, merge

#747 YH-867: adding tests for the component
  src/shared/ui/GradeChip/GradeChip.test.tsx
  src/shared/ui/GradeChip/GradeChip.tsx
Labels: review

#766 YH-861: add tests for Card
  src/shared/config/i18n/i18nTranslations.ts
  src/shared/ui/Card/Card.test.tsx
  src/shared/ui/Card/Card.tsx
  src/shared/ui/Text/Text.tsx
Labels: merge, tests

#771 YH-1213: display all questions without restrictions for admin
  src/pages/admin/CollectionPage/ui/CollectionPage.tsx
  src/widgets/Collection/ui/CollectionBody/CollectionBody.tsx
Labels: bug, merge

#768 YH-1208: added information about spam messages.
  public/locales/en/profile.json
  public/locales/ru/profile.json
  src/app/styles/variables/pallete.css
  src/app/styles/variables/themes.css
  src/features/profile/confirmationEmail/ui/ConfirmationEmail.module.css
  src/features/profile/confirmationEmail/ui/ConfirmationEmail.tsx
  src/shared/config/i18n/i18nTranslations.ts
  src/shared/ui/Button/Button.module.css
Labels: feature, comments
