Repository YeaHubTeam/yeahub-platform, pull requests merged in 2025-09, with the labels that each got.

#841 Feature/migration to k8s
  .github/workflows/deploy.yml
  Dockerfile
  nginx/custom_body_size.conf
  nginx/yeahub_default.conf
  src/widgets/authentication/login/ui/LoginCreateForm/LoginCreateForm.tsx
  src/widgets/registration/ui/UserCreateForm.tsx
Labels: review, feature

#820 YH-1293: update toast styles
  src/shared/ui/Toast/CloseBtn.tsx
  src/shared/ui/Toast/Error.tsx
  src/shared/ui/Toast/Success.tsx
  src/shared/ui/Toast/Toast.module.css
  src/shared/ui/Toast/Toast.tsx
  src/shared/ui/Toast/Warning.tsx
  src/shared/ui/Toast/constants.ts
  src/shared/ui/Toast/styles.module.css
  src/shared/ui/Toast/types.ts
Labels: feature, merge

#834 YH-1296: added show to image skill in question
  src/entities/question/index.ts
  src/entities/question/model/lib/getQuestionImage.ts
  src/widgets/question/QuestionHeader/ui/QuestionHeader.tsx
  src/widgets/question/QuestionsList/ui/PreviewQuestionsItem/PreviewQuestionsItem.tsx
Labels: feature, merge

#832 YH-1283: Add break-word rule in Card.module.css
  src/shared/ui/Card/Card.module.css
Labels: bug, merge

#833 YH-1284: fix unique key
  src/entities/socialNetwork/ui/SocialNetWorkList/SocialNetWorkList.tsx
Labels: bug, merge

#848 YH-1316: move paste plugin registration to onCreate
  src/shared/ui/TextEditor/TextEditor.tsx
Labels: bug, merge

#823 YH-1298: Made corrections to the resource table
  public/locales/en/resources.json
  public/locales/ru/resources.json
  src/shared/config/i18n/i18nTranslations.ts
  src/widgets/resources/ResourcesTable/ui/ResourcesTable.tsx
Labels: bug, merge

#847 YH-1000: add skeleton to collection block, connect skeleton to landing page
  src/app/layouts/LandingLayout/model/helper/SkeletonGenerator.tsx
  src/entities/collection/ui/CollectionPreview/CollectionPreview.sekeleton.tsx
  src/pages/landing/LandingPage/ui/LandingPage.skeleton.tsx
  src/widgets/Landing/CollectionBlock/index.ts
  src/widgets/Landing/CollectionBlock/ui/AdditionalBlock/AdditionalBlock.skeleton.tsx
  src/widgets/Landing/CollectionBlock/ui/CollectionBlock/CollectionBlock.skeleton.tsx
  src/widgets/Landing/CollectionBlock/ui/FilterChip/FilterChip.skeleton.tsx
  src/widgets/Landing/CollectionBlock/ui/FiltersBlock/FiltersBlock.skeleton.tsx
  src/widgets/Landing/CollectionBlock/ui/MainBlock/MainBlock.skeleton.tsx
Labels: feature, merge

#852 YH-875: add tests to Text component
  src/shared/ui/Text/Text.test.tsx
Labels: feature, merge

#857 YH-1327: add mock request to fetch collections list
  src/app/msw/handlers.ts
  src/entities/collection/api/__mock__/collectionListMock.ts
  src/entities/collection/api/__mock__/data/collectionsMock.ts
  src/entities/collection/api/__mock__/index.ts
  src/entities/collection/index.ts
Labels: feature, merge

#861 YH-1343: refactor finish quiz
  src/entities/quiz/api/quizApi.ts
  src/entities/quiz/index.ts
  src/entities/quiz/model/constants/quizConstants.ts
  src/features/collections/trainCollection/ui/TrainCollectionButton.tsx
  src/features/quiz/cloneQuiz/ui/CloneQuizButton/CloneQuizButton.tsx
  src/features/quiz/finishQuiz/api/finishQuizApi.ts
  src/features/quiz/finishQuiz/index.ts
  src/features/quiz/finishQuiz/model/constants/finishQuizConstants.ts
  src/features/quiz/finishQuiz/model/types/finishQuizTypes.ts
  src/features/quiz/finishQuiz/ui/FinishQuizButton/FinishQuizButton.tsx
  src/features/quiz/interruptQuiz/ui/InterruptQuizButton/InterruptQuizButton.tsx
  src/pages/interview/CreateQuizPage/ui/CreateQuizPage.tsx
  src/pages/interview/InterviewQuizPage/ui/InterviewQuizPage.module.css
  src/pages/interview/InterviewQuizPage/ui/InterviewQuizPage.tsx
Labels: feature, merge

#862 YH-1329: follow links for registered users
  src/widgets/Landing/Header/model/constants/headerConstants.ts
  src/widgets/Landing/Header/ui/Header/Header.tsx
  src/widgets/Landing/Header/ui/HeaderNav/HeaderNavDesktop/HeaderNavDesktop.tsx
  src/widgets/Landing/Header/ui/HeaderNav/HeaderNavMobile/HeaderNavMobile.tsx
Labels: feature, merge

#866 YH-1328: fix in CollectionPreview wrapped the collection in a Link
  src/entities/collection/ui/CollectionPreview/CollectionPreview.tsx
Labels: bug, merge

#871 YH-1351: made the name field in the profile optional
  src/features/profile/editProfileForm/model/lib/helpers/editProfileFormHelpers.ts
  src/features/profile/editProfileForm/model/lib/validation/editProfileSchema.ts
Labels: feature, merge

#868 YH-870: add tests to KeywordList component
  src/app/layouts/LandingLayout/ui/LandingLayout.test.tsx
  src/app/providers/router/config/routeConfig.tsx
  src/shared/ui/KeywordsList/KeywordsList.test.tsx
  src/shared/ui/KeywordsList/KeywordsList.tsx
  src/widgets/Landing/Footer/ui/FooterLinks/FooterLinks.skeleton.test.tsx
  src/widgets/Landing/Footer/ui/FooterLinks/FooterLinks.skeleton.tsx
  src/widgets/authentication/login/ui/LoginCreateForm/LoginCreateForm.tsx
  src/widgets/registration/ui/UserCreateForm.tsx
Labels: merge, tests

#883 YH-1351: fix email validation
  src/features/profile/editProfileForm/model/lib/validation/editProfileSchema.ts
Labels: bug, merge

#884 YH-1381: refactor select skills for filters
  src/entities/collection/ui/ChooseCollectionSpecialization/ChooseCollectionSpecialization.tsx
  src/entities/question/index.ts
  src/entities/question/ui/ChooseQuestionsCategories/ChooseQuestionsCategories.module.css
  src/entities/question/ui/ChooseQuestionsCategories/ChooseQuestionsCategories.skeleton.tsx
  src/entities/question/ui/ChooseQuestionsCategories/ChooseQuestionsCategories.tsx
  src/entities/skill/index.ts
  src/entities/skill/model/constants/skillConstants.ts
  src/entities/skill/ui/SkillsListField/SkillsListField.skeleton.tsx
  src/entities/skill/ui/SkillsListField/SkillsListField.tsx
  src/entities/specialization/ui/SpecializationsListField/SpecializationsListField.tsx
  src/features/question/questionsFilterSet/ui/QuestionsFilterSet.tsx
  src/pages/interview/CollectionsPage/ui/CollectionsPage/CollectionsPage.tsx
  src/pages/interview/CreateQuizPage/ui/CreateQuizPage.tsx
  src/pages/interview/QuestionsPage/ui/QuestionsPage/QuestionsPage.tsx
  src/pages/landing/CreatePublicQuizPage/ui/CreatePublicQuizPage.tsx
  src/pages/landing/PublicQuestionsPage/ui/PublicQuestionsFilterPanel/PublicQuestionsFilterPanel.skeleton.tsx
  src/pages/landing/PublicQuestionsPage/ui/PublicQuestionsFilterPanel/PublicQuestionsFilterPanel.tsx
  src/pages/landing/PublicQuestionsPage/ui/PublicQuestionsPage/PublicQuestionsPage.tsx
  src/widgets/Marketplace/ui/MarketplaceFiltersPanel/MarketplaceFiltersPanel.skeleton.tsx
  src/widgets/Marketplace/ui/MarketplaceFiltersPanel/MarketplaceFiltersPanel.tsx
  src/widgets/question/QuestionsFilterPanel/ui/QuestionsFilterPanel.skeleton.tsx
  src/widgets/question/QuestionsFilterPanel/ui/QuestionsFilterPanel.tsx
Labels: feature, merge

#875 YH-1333: updated the widget for completed interview questions
  src/shared/ui/Icon/icons.ts
  src/shared/ui/Icon/types.ts
  src/widgets/interview/PassedQuestionsList/ui/PassedQuestionsItem/PassedQuestionsItem.module.css
  src/widgets/interview/PassedQuestionsList/ui/PassedQuestionsItem/PassedQuestionsItem.tsx
  src/widgets/interview/PassedQuestionsList/ui/PassedQuestionsList/PassedQuestionsList.module.css
Labels: feature, merge

#889 fix/YH-1344
  src/widgets/interview/QuizAdditionalInfo/ui/QuizAdditionalInfo/QuizAdditionalInfo.tsx
Labels: bug, merge

#892 YH-1370: added filters to the my resources page
  src/entities/resource/api/resourceApi.ts
  src/entities/resource/index.ts
  src/entities/resource/model/types/filters.ts
  src/entities/resource/model/types/resource.ts
  src/pages/interview/QuestionsPage/ui/QuestionsPage/QuestionsPage.tsx
  src/pages/wiki/MyResourcesPage/ui/MyResourcesPage.tsx
  src/pages/wiki/MyResourcesPage/ui/MyResourcesPageSkeleton.skeleton.tsx
  src/shared/assets/icons/burgerAndCross.svg
  src/shared/assets/icons/cross.svg
  src/shared/config/i18n/i18nTranslations.ts
  src/shared/hooks/useQueryFilter.ts
  src/shared/ui/BaseFilterSection/BaseFilterSection.tsx
  src/shared/ui/Icon/icons.ts
  src/shared/ui/Icon/types.ts
  src/widgets/Marketplace/index.ts
  src/widgets/Marketplace/model/hooks/useMarketplaceFilters.ts
  src/widgets/Marketplace/ui/MyResourcesFiltersPanel/MyResourcesFiltersPanel.tsx
  src/widgets/Marketplace/ui/ResourcesStatusBlock/ResourcesStatusBlock.module.css
  src/widgets/Marketplace/ui/ResourcesStatusBlock/ResourcesStatusBlock.tsx
  src/widgets/question/QuestionsFilterPanel/ui/QuestionsFilterPanel.tsx
Labels: feature, merge

#881 YH-1312: Create page with list of requests for the resource
  public/locales/en/resources.json
  public/locales/ru/resources.json
  src/app/providers/router/config/routeConfig.tsx
  src/app/providers/store/config/config.ts
  src/entities/resource/api/resourceApi.ts
  src/entities/resource/index.ts
  src/entities/resource/model/constants/resource.ts
  src/entities/resource/model/types/resource.ts
  src/entities/resource/model/types/resourceRequest.ts
  src/entities/resource/ui/ResourceRequestStatus/ResourceRequestStatus.tsx
  src/pages/admin/ResourcesRequestsTablePage/index.ts
  src/pages/admin/ResourcesRequestsTablePage/model/selectors/resourcesRequestsTablePageSelectors.ts
  src/pages/admin/ResourcesRequestsTablePage/model/slice/resourcesRequestsPageSlice.ts
  src/pages/admin/ResourcesRequestsTablePage/model/types/resourcesRequestsTablePageTypes.ts
  src/pages/admin/ResourcesRequestsTablePage/ui/ResourcesRequestsTablePage/ResourcesRequestsTablePage.module.css
  src/pages/admin/ResourcesRequestsTablePage/ui/ResourcesRequestsTablePage/ResourcesRequestsTablePage.tsx
  src/pages/admin/ResourcesRequestsTablePage/ui/ResourcesRequestsTablePagePagination/ResourcesRequestsTablePagePagination.module.css
  src/pages/admin/ResourcesRequestsTablePage/ui/ResourcesRequestsTablePagePagination/ResourcesRequestsTablePagePagination.tsx
  src/shared/config/api/apiTags.ts
  src/shared/config/i18n/i18n.ts
  src/shared/config/i18n/i18nTranslations.ts
  src/shared/config/router/routes.ts
  src/shared/config/store/State.ts
  src/widgets/resources/ResourceRequestsTable/ui/ResourceRequestsTable.module.css
  src/widgets/resources/ResourceRequestsTable/ui/ResourceRequestsTable.tsx
  src/widgets/resources/index.ts
Labels: feature, comments
