Repository YeaHubTeam/yeahub-platform, pull requests merged in 2025-08, with the labels that each got.

#774 YH-1214: expanded clickable area of Tiptap editor
  src/shared/ui/TextEditor/TextEditor.tsx
Labels: bug, merge

#785 YH-1238: fix cancelled button for user status = canceled
  src/widgets/Profile/ui/SubscriptionTab/ui/PremiumSubscriptionTab/PremiumSubscriptionTab.tsx
Labels: bug, merge

#773 Feature: YH-1211 - Connect API to create resource form
  public/locales/ru/translation.json
  src/entities/resource/model/types/resource.ts
  src/entities/resource/ui/ResourceForm/ResourceForm.tsx
  src/entities/resource/ui/ResourceSelect/ResourceSelect.tsx
  src/features/resources/createResource/api/createResourceApi.ts
  src/features/resources/createResource/index.ts
  src/features/resources/createResource/model/constants/createResourceConstants.ts
  src/features/resources/createResource/model/lib/validation/resourceCreateSchema.ts
  src/features/resources/createResource/model/types/resourceCreateTypes.ts
  src/features/resources/createResource/ui/ResourceCreateForm/ResourceCreateForm.tsx
  src/features/resources/createResource/ui/ResourceCreateFormWithHeader/ResourceCreateFormWithHeader.module.css
  src/features/resources/createResource/ui/ResourceCreateFormWithHeader/ResourceCreateFormWithHeader.tsx
  src/pages/landing/PublicMarketplaceRequestPage/ui/PublicMarketplaceRequestPage.tsx
  src/shared/config/i18n/i18nTranslations.ts
  src/shared/config/router/routes.ts
Labels: feature, merge

#790 YH-1241: fixed the request for specializations
  src/entities/media/model/types/media.ts
  src/pages/profile/UserProfilePage/ui/UserProfilePage.tsx
Labels: bug, merge

#789 YH-1243: fix(styles): remove background-color: inherit in collection preview and fix duplicate :disabled selector in button
  src/entities/collection/ui/CollectionPreview/CollectionPreview.module.css
  src/shared/ui/Button/Button.module.css
Labels: bug, merge

#788 YH-367: fixed editing and deleting collection by admin
  src/entities/profile/index.ts
  src/entities/profile/model/selectors/profileSelectors.ts
  src/features/collections/editCollection/ui/CollectionEditForm/CollectionEditForm.tsx
  src/pages/admin/CollectionEditPage/ui/CollectionEditPage.tsx
  src/pages/admin/CollectionPage/ui/CollectionPage.tsx
  src/pages/admin/CollectionsPage/ui/CollectionsPage/CollectionsPage.tsx
Labels: bug, merge, comments

#800 YH-1260: fix title changes when subscription is cancelled
  src/entities/subscription/model/types/subscription.ts
  src/widgets/Profile/ui/SubscriptionTab/ui/PremiumSubscriptionTab/PremiumSubscriptionTab.tsx
Labels: bug, merge

#798 YH-1152: add Onboarding modal
  public/locales/en/onboarding.json
  public/locales/ru/onboarding.json
  src/features/profile/editProfileForm/api/editProfileApi.ts
  src/features/profile/editProfileForm/index.ts
  src/features/profile/editProfileForm/ui/EditProfileForm/EditProfileForm.tsx
  src/pages/interview/MainPage/ui/MainPage.tsx
  src/shared/assets/icons/checkList.svg
  src/shared/assets/icons/graphUp.svg
  src/shared/assets/icons/handShake.svg
  src/shared/assets/icons/keySquare.svg
  src/shared/config/i18n/i18n.ts
  src/shared/config/i18n/i18nTranslations.ts
  src/shared/ui/Icon/icons.ts
  src/shared/ui/Icon/types.ts
  src/shared/ui/Icons/StepIndicatorIcon/StepIndicatorIcon.tsx
  src/shared/ui/Icons/StepIndicatorIcon/index.ts
  src/shared/ui/Modal/Modal.module.css
  src/shared/ui/Modal/Modal.tsx
  src/shared/ui/Modal/ModalTypes.ts
  src/shared/ui/Stepper/Stepper.module.css
  src/shared/ui/Stepper/Stepper.stories.tsx
  src/shared/ui/Stepper/Stepper.tsx
  src/widgets/Main/OnboardingModal/index.ts
  src/widgets/Main/OnboardingModal/model/assets/sealCheck.avif
  src/widgets/Main/OnboardingModal/model/types/types.ts
  src/widgets/Main/OnboardingModal/ui/AdvantagesBlock/AdvantagesBlock.module.css
  src/widgets/Main/OnboardingModal/ui/AdvantagesBlock/AdvantagesBlock.tsx
  src/widgets/Main/OnboardingModal/ui/ChooseSpecializationStep/ChooseSpecializationStep.module.css
  src/widgets/Main/OnboardingModal/ui/ChooseSpecializationStep/ChooseSpecializationStep.tsx
  src/widgets/Main/OnboardingModal/ui/FinalStep/FinalStep/FinalStep.module.css
  src/widgets/Main/OnboardingModal/ui/FinalStep/FinalStep/FinalStep.tsx
  src/widgets/Main/OnboardingModal/ui/FinalStep/NavigationBlock/NavigationBlock.module.css
  src/widgets/Main/OnboardingModal/ui/FinalStep/NavigationBlock/NavigationBlock.tsx
  src/widgets/Main/OnboardingModal/ui/GreetingStep/GreetingStep.module.css
  src/widgets/Main/OnboardingModal/ui/GreetingStep/GreetingStep.tsx
  src/widgets/Main/OnboardingModal/ui/LayoutStepComponent/LayoutStepComponent.module.css
  src/widgets/Main/OnboardingModal/ui/LayoutStepComponent/LayoutStepComponent.tsx
  src/widgets/Main/OnboardingModal/ui/OnboardingHeader/OnboadringProgress/OnboardingProgress.module.css
  src/widgets/Main/OnboardingModal/ui/OnboardingHeader/OnboadringProgress/OnboardingProgress.tsx
  src/widgets/Main/OnboardingModal/ui/OnboardingHeader/OnboardingHeader/OnboardingHeader.tsx
  src/widgets/Main/OnboardingModal/ui/OnboardingModal/OnboardingModal.module.css
  src/widgets/Main/OnboardingModal/ui/OnboardingModal/OnboardingModal.tsx
  src/widgets/Main/OnboardingModal/ui/ServiceOverviewStep/ServiceOverviewStep.tsx
  src/widgets/Main/OnboardingModal/ui/SubscriptionBenefitsStep/SubscriptionBenefitsStep.tsx
Labels: feature, comments

#801 YH-1261: resources page
  public/locales/en/resources.json
  public/locales/ru/resources.json
  public/locales/ru/translation.json
  src/app/providers/router/config/routeConfig.tsx
  src/app/providers/store/config/config.ts
  src/pages/admin/ResourcesTablePage/index.ts
  src/pages/admin/ResourcesTablePage/model/selectors/resourcesTablePageSelectors.ts
  src/pages/admin/ResourcesTablePage/model/slice/resourcesTablePageSlice.ts
  src/pages/admin/ResourcesTablePage/model/types/resourcesTablePageTypes.ts
  src/pages/admin/ResourcesTablePage/ui/ResourcesTablePage/ResourcesTablePage.lazy.tsx
  src/pages/admin/ResourcesTablePage/ui/ResourcesTablePage/ResourcesTablePage.module.css
  src/pages/admin/ResourcesTablePage/ui/ResourcesTablePage/ResourcesTablePage.skeleton.tsx
  src/pages/admin/ResourcesTablePage/ui/ResourcesTablePage/ResourcesTablePage.tsx
  src/pages/admin/ResourcesTablePage/ui/ResourcesTablePagePagination/ResourcesTablePagePagination.module.css
  src/pages/admin/ResourcesTablePage/ui/ResourcesTablePagePagination/ResourcesTablePagePagination.tsx
  src/shared/assets/icons/books.svg
  src/shared/config/i18n/i18n.ts
  src/shared/config/i18n/i18nTranslations.ts
  src/shared/config/store/State.ts
  src/widgets/resources/ResourcesTable/ui/ResourcesTable.tsx
  src/widgets/resources/index.ts
Labels: feature, merge

#792 YH-1242: queries: useGetHistoryQuizQuery, useGetProfileQuizStatsQuery…
  src/pages/interview/InterviewPage/ui/InterviewPage.tsx
  src/widgets/interview/PassedQuizzesList/ui/PreviewPassedQuizzesList/PreviewPassedQuizzesList.tsx
  src/widgets/interview/QuestionsStatistic/ui/PreviewQuestionsStatistic/PreviewQuestionsStatistic.tsx
Labels: bug, merge

#806 YH-1269: redirect to email veritify
  src/features/subscriptions/trial/ui/TrialButton.tsx
Labels: bug, merge

#795 YH-853: hide skills field when no specialization selected in Question…
  src/entities/question/ui/QuestionForm/QuestionForm.tsx
Labels: review, feature

#797 YH-854: add emptySlot to Table and EmptyStub rendering inside tbody
  src/pages/admin/QuestionsTablePage/model/slices/questionsTablePageSlice.ts
  src/pages/admin/QuestionsTablePage/ui/QuestionsTablePage/QuestionsTablePage.tsx
  src/shared/ui/Tooltip/Tooltip.module.css
Labels: conflicts, feature, merge

#805 YH-1263: Replaced mock data with a request to get resource types
  src/entities/resource/api/resourceApi.ts
  src/entities/resource/model/constants/resource.ts
  src/entities/resource/model/types/resource.ts
  src/entities/resource/ui/ResourceSelect/ResourceSelect.tsx
  src/shared/config/api/apiTags.ts
  src/shared/config/i18n/i18nTranslations.ts
Labels: bug, merge

#810 YH-1268: added ResourcesTablePageRequest to routeConfig and transform some types for POST query
  public/locales/en/onboarding.json
  public/locales/ru/onboarding.json
  src/app/providers/router/config/routeConfig.tsx
  src/entities/resource/ui/ResourceForm/ResourceForm.tsx
  src/features/resources/createResource/model/lib/map/toCreateResourceBody.ts
  src/features/resources/createResource/model/types/resourceCreateTypes.ts
  src/features/resources/createResource/ui/ResourceCreateFormWithHeader/ResourceCreateFormWithHeader.tsx
  src/pages/admin/ResourceCreatePage/index.ts
  src/pages/admin/ResourceCreatePage/ui/ResourceCreatePage.lazy.ts
  src/pages/admin/ResourceCreatePage/ui/ResourceCreatePage.tsx
  src/pages/landing/PublicMarketplaceRequestPage/ui/PublicMarketplaceRequestPage.tsx
Labels: feature, merge

#829 YH-1287: update interface after successful activation trial subscription
  src/features/subscriptions/subscribe/ui/AgreementForm/AgreementForm.tsx
  src/features/subscriptions/trial/api/getTrial.ts
  src/shared/ui/Tabs/hooks.ts
Labels: bug, merge

#818 YH-1282: corrected landing page layout
  public/locales/ru/landing.json
  src/shared/ui/Chip/Chip.module.css
  src/widgets/Landing/AboutQuestionsBlock/ui/SkillChip/SkillChip.module.css
  src/widgets/Landing/AboutQuestionsBlock/ui/SkillsListTicker/SkillsListTicker.tsx
  src/widgets/Landing/BannerBlock/ui/BannerImage/BannerImage.module.css
  src/widgets/Landing/HistoryBlock/ui/HistoryTextBlock/HistoryTextBlock.module.css
  src/widgets/Landing/InterviewTrainerBlock/ui/InterviewCard/InterviewCard.module.css
  src/widgets/Landing/InterviewTrainerBlock/ui/MainBlock/MainBlock.module.css
Labels: bug, merge

#835 YH-1301: hide telegram auth
  src/widgets/authentication/login/ui/LoginCreateForm/LoginCreateForm.tsx
  src/widgets/registration/ui/UserCreateForm.tsx
Labels: bug, merge
