Repository YeaHubTeam/yeahub-platform, pull requests merged in 2025-06, with the labels that each got.

#665 YH-996: feature add skeleton to landing page banner
  src/pages/landing/LandingPage/ui/LandingPage.skeleton.tsx
  src/widgets/Landing/BannerBlock/index.ts
  src/widgets/Landing/BannerBlock/ui/AvatarGroup/AvatarGroup.module.css
  src/widgets/Landing/BannerBlock/ui/AvatarGroup/AvatarGroup.skeleton.tsx
  src/widgets/Landing/BannerBlock/ui/BannerBlock/BannerBlock.module.css
  src/widgets/Landing/BannerBlock/ui/BannerBlock/BannerBlock.skeleton.tsx
  src/widgets/Landing/BannerBlock/ui/BannerButton/BannerButton.skeleton.tsx
  src/widgets/Landing/BannerBlock/ui/BannerContent/BannerContent.skeleton.tsx
  src/widgets/Landing/BannerBlock/ui/BannerImage/BannerImage.skeleton.tsx
  src/widgets/Landing/BannerBlock/ui/BlockDescription/BlockDescription.skeleton.tsx
  src/widgets/Landing/BannerBlock/ui/BlockTitle/BlockTitle.skeleton.tsx
  src/widgets/Landing/BannerBlock/ui/Sticker/Sticker.skeleton.tsx
  src/widgets/Landing/BannerBlock/ui/Sticker/Sticker.tsx
Labels: feature, comments

#667 YH-1012: Guru's Promotion System
  public/locales/en/guru.json
  public/locales/ru/guru.json
  src/entities/guru/index.ts
  src/entities/guru/model/constants/gurus.ts
  src/entities/guru/model/helpers/getGuruWithMatchingSpecialization.ts
  src/entities/guru/model/helpers/getRandomGurus.ts
  src/entities/guru/model/types/guru.ts
  src/entities/guru/ui/GuruSocialsList/GuruSocialsList.module.css
  src/entities/guru/ui/GuruSocialsList/GuruSocialsList.tsx
  src/entities/guru/ui/GurusBanner/GurusBanner.tsx
  src/entities/guru/ui/GurusHeader/GurusHeader.module.css
  src/entities/guru/ui/GurusHeader/GurusHeader.tsx
  src/entities/guru/ui/GurusItem/GurusItem.module.css
  src/entities/guru/ui/GurusItem/GurusItem.tsx
  src/entities/guru/ui/GurusList/GurusList.module.css
  src/entities/guru/ui/GurusList/GurusList.tsx
  src/pages/interview/CollectionPage/ui/CollectionPage.tsx
  src/pages/interview/MainPage/ui/MainPage.module.css
  src/pages/interview/MainPage/ui/MainPage.tsx
  src/pages/interview/QuestionPage/ui/QuestionPage.tsx
  src/pages/landing/PublicCollectionPage/ui/PublicCollectionPage.module.css
  src/pages/landing/PublicCollectionPage/ui/PublicCollectionPage.tsx
  src/pages/landing/PublicQuestionPage/ui/PublicQuestionPage.module.css
  src/pages/landing/PublicQuestionPage/ui/PublicQuestionPage.tsx
  src/shared/assets/icons/listWithBackground.svg
  src/shared/assets/icons/telegramWithBackground.svg
  src/shared/assets/icons/userCheckWithBackground.svg
  src/shared/assets/icons/youtubeWithBackground.svg
  src/shared/config/i18n/i18n.ts
  src/shared/config/i18n/i18nTranslations.ts
  src/shared/ui/Avatar/Avatar.module.css
  src/shared/ui/Avatar/Avatar.tsx
  src/shared/ui/Avatar/index.ts
  src/shared/ui/Card/Card.module.css
  src/shared/ui/Card/Card.tsx
  src/shared/ui/Icon/icons.ts
  src/shared/ui/Icon/types.ts
  src/widgets/Collection/ui/AdditionalInfo/AdditionalInfo.tsx
  src/widgets/Landing/Footer/model/constants/footerConstants.ts
  src/widgets/Main/SubscribeToMedia/ui/SubscribeToMedia.module.css
  src/widgets/question/QuestionAdditionalInfo/ui/QuestionAdditionalInfo.tsx
Labels: feature, merge

#676 YH-1019: Add translate in FAQ block
  src/widgets/Profile/ui/SubscriptionTab/ui/FreeSubscriptionTab/FreeSubscriptionTab.tsx
Labels: bug, merge

#675 YH-1025: Fix profile roles view
  src/entities/guru/ui/GuruSocialsList/GuruSocialsList.module.css
  src/entities/guru/ui/GuruSocialsList/GuruSocialsList.tsx
  src/shared/ui/Flex/Flex.module.css
  src/shared/ui/Flex/Flex.tsx
  src/widgets/Profile/ui/UserCard/ui/UserBlock/UserBlock.module.css
  src/widgets/Profile/ui/UserCard/ui/UserBlock/UserBlock.tsx
  src/widgets/Profile/ui/UserCard/ui/UserInfoBlock/UserInfoBlock.tsx
Labels: bug, comments

#674 YH-1026: Update sidebar and popover profile links
  public/locales/en/translation.json
  public/locales/ru/translation.json
  src/app/providers/router/config/routeConfig.tsx
  src/app/styles/App.css
  src/shared/config/i18n/i18nTranslations.ts
  src/widgets/Header/ui/UserPreferences/UserPreferences.tsx
Labels: feature, merge

#673 YH-1028: Updating the design of the subscription selection tab
  public/locales/en/subscriptionCard.json
  public/locales/ru/subscriptionCard.json
  src/widgets/FaqList/ui/FaqItem/FaqItem.module.css
  src/widgets/Profile/ui/SubscriptionTab/ui/FreeSubscriptionTab/FreeSubscriptionTab.tsx
Labels: review, feature, comments

#682 YH-1039: add subscription access warning component
  public/locales/en/subscription.json
  public/locales/ru/subscription.json
  src/shared/config/i18n/i18nTranslations.ts
  src/widgets/Profile/ui/SubscriptionTab/ui/PremiumSubscriptionTab/PremiumSubscriptionTab.module.css
  src/widgets/Profile/ui/SubscriptionTab/ui/PremiumSubscriptionTab/PremiumSubscriptionTab.tsx
Labels: feature, merge

#683 YH-735: Added an optional check for the role in CollectionBody.
  src/pages/interview/CollectionPage/ui/CollectionPage.tsx
  src/widgets/Collection/ui/CollectionBody/CollectionBody.tsx
Labels: feature, merge

#686 YH-1055: add terminal key env variable
  src/features/subscriptions/subscribe/ui/SubscribeButton/ui/SubscribeButton.tsx
Labels: feature, merge

#687 YH-1027: add change design
  src/widgets/Profile/ui/SubscriptionTab/ui/PayHistoryItem/PayHistoryItem.module.css
  src/widgets/Profile/ui/SubscriptionTab/ui/PayHistoryItem/PayHistoryItem.tsx
  src/widgets/Profile/ui/SubscriptionTab/ui/PayHistoryList/PayHistoryList.module.css
  src/widgets/Profile/ui/SubscriptionTab/ui/PayHistoryList/PayHistoryList.tsx
  src/widgets/Profile/ui/SubscriptionTab/ui/PremiumSubscriptionTab/PremiumSubscriptionTab.module.css
  src/widgets/Profile/ui/SubscriptionTab/ui/PremiumSubscriptionTab/PremiumSubscriptionTab.tsx
  src/widgets/Profile/ui/SubscriptionTab/ui/SubscriptionPagination/SubscriptionPagination.module.css
Labels: feature, merge

#679 YH-1017: update question list styles
  src/pages/interview/QuestionsPage/ui/QuestionsPagePagination/QuestionPagePagination.module.css
  src/pages/landing/PublicQuestionsPage/ui/PublicQuestionsPagePagination/PublicQuestionPagePagination.module.css
  src/shared/ui/Accordion/ui/Accordion.module.css
  src/shared/ui/Accordion/ui/Accordion.tsx
  src/shared/ui/Card/Card.module.css
  src/widgets/question/QuestionsList/ui/FullQuestionsList/FullQuestionsList.module.css
  src/widgets/question/QuestionsList/ui/FullQuestionsList/FullQuestionsList.tsx
Labels: feature, merge

#697 [YH-1071] Изменение логики покупки подписки, вынос всего на сервер
  public/locales/en/translation.json
  public/locales/ru/translation.json
  src/features/subscriptions/subscribe/ui/SubscribeButton/api/getNewSubscriptionOrderId.ts
  src/features/subscriptions/subscribe/ui/SubscribeButton/api/getPaymentUrl.ts
  src/features/subscriptions/subscribe/ui/SubscribeButton/model/constants/subscribeButtonConstants.ts
  src/features/subscriptions/subscribe/ui/SubscribeButton/ui/SubscribeButton.tsx
  src/shared/config/i18n/i18nTranslations.ts
  webpack.config.ts
Labels: review, feature

#698 YH-1059: A translation has been added for the author role and styles …
  public/locales/en/user.json
  public/locales/ru/user.json
  src/entities/user/model/types/user.ts
  src/shared/config/i18n/i18nTranslations.ts
  src/widgets/UsersTable/ui/UsersTable.module.css
Labels: feature, merge

#703 YH-1050: Add a wrapper to stub questions
  src/widgets/question/QuestionsList/ui/PreviewQuestionsList/PreviewQuestionsList.tsx
Labels: feature, merge

#702 YH-1044: Profile correction
  src/entities/user/ui/UserEditButton/UserEditButton.tsx
  src/shared/ui/AvatarWithoutPhoto/AvatarWithoutPhoto.module.css
  src/shared/ui/ImageLoader/ImageLoader.module.css
  src/widgets/Profile/ui/UserCard/ui/UserBlock/UserBlock.module.css
  src/widgets/Profile/ui/UserCard/ui/UserImageBlock/UserImageBlock.module.css
  src/widgets/Profile/ui/UserCard/ui/UserInfoBlock/UserInfoBlock.module.css
  src/widgets/Profile/ui/UserCard/ui/UserInfoBlock/UserInfoBlock.tsx
Labels: feature, merge

#701 YH-1051: changed gauge color, added question stats, activated user bu…
  src/shared/ui/charts/GaugeChart/GaugeChart.tsx
  src/widgets/interview/QuestionsStatistic/model/lib/getQuestionsStats/getQuestionsStats.ts
  src/widgets/interview/QuestionsStatistic/ui/PreviewQuestionsStatistic/PreviewQuestionsStatistic.tsx
Labels: bug, review

#685 YH-940: added story and taking screenshots of the CollectionBlock
  .loki/reference/chrome_iphone7_widgets_Landing_CollectionBlock_AdditionalBlock_Primary.png
  .loki/reference/chrome_iphone7_widgets_Landing_CollectionBlock_FilterChip_Default.png
  .loki/reference/chrome_iphone7_widgets_Landing_CollectionBlock_FilterChip_With_Long_Text.png
  .loki/reference/chrome_iphone7_widgets_Landing_CollectionBlock_FiltersBlock_Primary.png
  .loki/reference/chrome_iphone7_widgets_Landing_CollectionBlock_FiltersBlock_With_Custom_Filters.png
  .loki/reference/chrome_iphone7_widgets_Landing_CollectionBlock_FiltersBlock_With_Many_Filters.png
  .loki/reference/chrome_iphone7_widgets_Landing_CollectionBlock_MainBlock_Primary.png
  .loki/reference/chrome_iphone7_widgets_Landing_CollectionBlock_Primary.png
  .loki/reference/chrome_laptop_widgets_Landing_CollectionBlock_AdditionalBlock_Primary.png
  .loki/reference/chrome_laptop_widgets_Landing_CollectionBlock_FilterChip_Default.png
  .loki/reference/chrome_laptop_widgets_Landing_CollectionBlock_FilterChip_With_Long_Text.png
  .loki/reference/chrome_laptop_widgets_Landing_CollectionBlock_FiltersBlock_Primary.png
  .loki/reference/chrome_laptop_widgets_Landing_CollectionBlock_FiltersBlock_With_Custom_Filters.png
  .loki/reference/chrome_laptop_widgets_Landing_CollectionBlock_FiltersBlock_With_Many_Filters.png
  .loki/reference/chrome_laptop_widgets_Landing_CollectionBlock_MainBlock_Primary.png
  .loki/reference/chrome_laptop_widgets_Landing_CollectionBlock_Primary.png
  src/widgets/Landing/CollectionBlock/ui/AdditionalBlock/AdditionalBlock.stories.tsx
  src/widgets/Landing/CollectionBlock/ui/CollectionBlock/CollectionBlock.stories.tsx
  src/widgets/Landing/CollectionBlock/ui/FilterChip/FilterChip.stories.tsx
  src/widgets/Landing/CollectionBlock/ui/FiltersBlock/FiltersBlock.stories.tsx
  src/widgets/Landing/CollectionBlock/ui/MainBlock/MainBlock.stories.tsx
Labels: merge, tests

#691 YH-1023 — UI маркетплейса: карточки ресурсов на моках
  public/locales/en/marketplace.json
  public/locales/ru/marketplace.json
  src/entities/resource/api/__mock__/data/resourcesMock.ts
  src/entities/resource/index.ts
  src/entities/resource/model/types/resource.ts
  src/entities/resource/ui/ResourceCard/ResourceCard.module.css
  src/entities/resource/ui/ResourceCard/ResourceCard.tsx
  src/pages/landing/PublicMarketplacePage/ui/PublicMarketplacePage.module.css
  src/pages/landing/PublicMarketplacePage/ui/PublicMarketplacePage.tsx
  src/shared/config/i18n/i18n.ts
  src/shared/config/i18n/i18nTranslations.ts
  src/widgets/Marketplace/index.ts
  src/widgets/Marketplace/ui/RecourcesList/ResourcesList.tsx
Labels: conflicts, feature, merge

#694 YH-999 :adds a skeleton for the simulator block on the landing page
  src/pages/landing/LandingPage/ui/LandingPage.skeleton.tsx
  src/widgets/Landing/InterviewTrainerBlock/index.ts
  src/widgets/Landing/InterviewTrainerBlock/ui/AdditionalBlock/AdditionalBlock.module.css
  src/widgets/Landing/InterviewTrainerBlock/ui/AdditionalBlock/AdditionalBlock.skeleton.tsx
  src/widgets/Landing/InterviewTrainerBlock/ui/InterviewCard/InterviewCard.skeleton.tsx
  src/widgets/Landing/InterviewTrainerBlock/ui/InterviewTrainerBlock/InterviewTrainerBlock.module.css
  src/widgets/Landing/InterviewTrainerBlock/ui/InterviewTrainerBlock/InterviewTrainerBlock.skeleton.tsx
  src/widgets/Landing/InterviewTrainerBlock/ui/MainBlock/MainBlock.module.css
  src/widgets/Landing/InterviewTrainerBlock/ui/MainBlock/MainBlock.skeleton.tsx
Labels: feature, merge

#707 Fix/YH-1100
  src/shared/config/sentry/ErrorBoundary.tsx
  src/shared/config/sentry/sentry.ts
  src/shared/config/sentry/sentryApiErrorMiddleware.ts
Labels: bug

#712 YH-1001: adds a skeleton for the history block on the landing page
  src/pages/landing/LandingPage/ui/LandingPage.skeleton.tsx
  src/widgets/Landing/HistoryBlock/index.ts
  src/widgets/Landing/HistoryBlock/ui/HistoryBlock/HistoryBlock.module.css
  src/widgets/Landing/HistoryBlock/ui/HistoryBlock/HistoryBlock.skeleton.tsx
  src/widgets/Landing/HistoryBlock/ui/HistorySlide/HistorySlide.skeleton.tsx
  src/widgets/Landing/HistoryBlock/ui/HistorySliderBlock/HistorySliderBlock.module.css
  src/widgets/Landing/HistoryBlock/ui/HistorySliderBlock/HistorySliderBlock.skeleton.tsx
  src/widgets/Landing/HistoryBlock/ui/HistoryTextBlock/HistoryTextBlock.module.css
  src/widgets/Landing/HistoryBlock/ui/HistoryTextBlock/HistoryTextBlock.skeleton.tsx
Labels: feature, merge

#669 YH-981: made a favorites system
  public/locales/en/questions.json
  public/locales/en/translation.json
  public/locales/ru/questions.json
  public/locales/ru/translation.json
  src/entities/question/model/types/question.ts
  src/entities/quiz/api/quizApi.ts
  src/entities/quiz/model/types/quiz.ts
  src/entities/resource/model/types.ts
  src/features/question/favoriteQuestion/api/favoriteQuestionApi.ts
  src/features/question/favoriteQuestion/index.ts
  src/features/question/favoriteQuestion/model/constants/favoriteQuestionConstants.ts
  src/features/question/favoriteQuestion/model/types/favoriteQuestionTypes.ts
  src/features/question/favoriteQuestion/ui/FavoriteQuestionButton.module.css
  src/features/question/favoriteQuestion/ui/FavoriteQuestionButton.skeleton.tsx
  src/features/question/favoriteQuestion/ui/FavoriteQuestionButton.tsx
  src/pages/interview/QuestionPage/ui/QuestionPage.tsx
  src/pages/interview/QuestionsPage/ui/QuestionsPage/QuestionsPage.tsx
  src/shared/assets/icons/favorite.svg
  src/shared/assets/icons/favoriteRed.svg
  src/shared/config/i18n/i18nTranslations.ts
  src/shared/hooks/useQueryFilter.ts
  src/shared/ui/Icon/icons.ts
  src/shared/ui/Icon/types.ts
  src/widgets/question/QuestionActions/ui/QuestionActions.skeleton.tsx
  src/widgets/question/QuestionActions/ui/QuestionActions.tsx
  src/widgets/question/QuestionsFilterPanel/model/types.ts
  src/widgets/question/QuestionsFilterPanel/ui/StatusFilterSection/StatusFilterSection.tsx
  src/widgets/question/QuestionsList/ui/FullQuestionItem/FullQuestionItem.tsx
Labels: feature, merge

#715 YH-1106: fix default specialization in edit profile
  src/entities/specialization/ui/SpecializationSelect/SpecializationSelect.module.css
  src/entities/specialization/ui/SpecializationSelect/SpecializationSelect.tsx
  src/shared/ui/Dropdown/Dropdown/Dropdown.tsx
  src/shared/ui/Dropdown/Select/Select.module.css
  src/shared/ui/Dropdown/Select/Select.tsx
Labels: bug, merge

#716 YH-1108: delete uikit
  package-lock.json
  package.json
  src/app/styles/App.css
  src/entities/collection/ui/CollectionForm/CollectionForm.module.css
  src/entities/collection/ui/CollectionForm/CollectionForm.tsx
  src/entities/company/ui/CompanyForm/CompanyForm.module.css
  src/entities/company/ui/CompanyForm/CompanyForm.tsx
  src/entities/company/ui/CompanySelect/CompanySelect.tsx
  src/entities/question/ui/QuestionForm/QuestionForm.tsx
  src/entities/skill/model/types/profileSkill.ts
  src/entities/skill/ui/SkillForm/SkillForm.tsx
  src/entities/skill/ui/SkillSelect/SkillSelect.tsx
  src/entities/socialNetwork/ui/SocialNetWorkList/SocialNetWorkList.tsx
  src/entities/specialization/index.ts
  src/entities/specialization/ui/SpecializationSelect/SpecializationSelect.tsx
  src/entities/specialization/utils/getSpecializationDefaultIcon.ts
  src/features/authentication/passwordRecovery/ui/PasswordRecoveryForm/PasswordRecoveryForm.tsx
  src/features/collections/trainCollection/ui/TrainCollectionButton.tsx
  src/features/profile/confirmationEmail/ui/ConfirmationEmail.tsx
  src/shared/ui/BackButton/BackButton.tsx
  src/shared/ui/FiltersDrawer/FiltersDrawer.tsx
  src/shared/ui/FormControl/FormControl.tsx
  src/shared/ui/IconButton/IconButton.module.css
  src/shared/ui/IconButton/IconButton.tsx
  src/shared/ui/SelectWithChips/SelectWithChips.tsx
  src/shared/ui/Table/Table.tsx
  src/widgets/SearchSection/ui/SearchSection.module.css
  src/widgets/interview/PassedQuestionsList/ui/PassedQuestionsItem/PassedQuestionsItem.tsx
Labels: feature, merge
