Repository YeaHubTeam/yeahub-platform, pull requests merged in 2025-04, with the labels that each got.

#580 Feature/YH-907: added page CompanyDetailPage
  public/locales/en/translation.json
  public/locales/ru/translation.json
  src/app/providers/router/config/routeConfig.tsx
  src/entities/company/api/companyApi.ts
  src/entities/company/index.ts
  src/entities/company/model/constants/companyConstants.ts
  src/entities/company/model/types/company.ts
  src/entities/company/ui/CompanyCard/CompanyCard.module.css
  src/entities/company/ui/CompanyCard/CompanyCard.tsx
  src/features/company/deleteCompany/api/deleteCompanyApi.ts
  src/features/company/deleteCompany/index.ts
  src/features/company/deleteCompany/model/constants/deleteCompanyConstants.ts
  src/features/company/deleteCompany/ui/DeleteCompanyButton/DeleteCompanyButton.tsx
  src/pages/admin/CompanyDetailPage/index.ts
  src/pages/admin/CompanyDetailPage/ui/CompanyDetailPage/CompanyDetailPage.lazy.tsx
  src/pages/admin/CompanyDetailPage/ui/CompanyDetailPage/CompanyDetailPage.tsx
  src/shared/config/api/apiTags.ts
  src/shared/config/i18n/i18nTranslations.ts
  src/shared/config/router/routes.ts
Labels: feature, merge

#583 YH-904: add page "create company"
  public/locales/en/company.json
  public/locales/ru/company.json
  public/locales/ru/translation.json
  src/app/providers/router/config/routeConfig.tsx
  src/entities/company/index.ts
  src/entities/company/model/types/company.ts
  src/entities/company/ui/CompanyForm/CompanyForm.module.css
  src/entities/company/ui/CompanyForm/CompanyForm.tsx
  src/features/company/createCompany/api/createCompanyApi.ts
  src/features/company/createCompany/index.ts
  src/features/company/createCompany/model/constants/createCompanyConstants.ts
  src/features/company/createCompany/model/lib/validation/companyCreateSchema.ts
  src/features/company/createCompany/model/types/companyCreateTypes.ts
  src/features/company/createCompany/ui/CompanyCreateForm/CompanyCreateForm.module.css
  src/features/company/createCompany/ui/CompanyCreateForm/CompanyCreateForm.tsx
  src/features/company/createCompany/ui/CompanyCreateFormHeader/CompanyCreateFormHeader.tsx
  src/pages/admin/CompanyCreatePage/index.ts
  src/pages/admin/CompanyCreatePage/ui/CompanyCreatePage.lazy.tsx
  src/pages/admin/CompanyCreatePage/ui/CompanyCreatePage.tsx
  src/shared/config/i18n/i18n.ts
  src/shared/config/i18n/i18nTranslations.ts
  src/shared/config/router/routes.ts
  src/shared/ui/Switch/ui/Switch.module.css
Labels: feature, merge

#560 Fix/yh 883
  src/shared/ui/Popover/PopoverMenu/PopoverMenu.tsx
Labels: conflicts, feature, merge

#582 YH-921: Fix incorrect author avatar and link logic
  src/entities/collection/api/__mock__/data/collectionsMock.ts
  src/entities/question/api/__mocks__/data/questionsMock.ts
  src/entities/question/index.ts
  src/entities/question/model/types/question.ts
  src/entities/question/ui/QuestionAuthor/QuestionAuthor.tsx
  src/features/question/createQuestion/api/__mocks__/data/newQuestionMock.ts
  src/widgets/Profile/ui/UserCard/ui/UserImageBlock/UserImageBlock.tsx
  src/widgets/question/QuestionAdditionalInfo/ui/QuestionAdditionalInfo.tsx
Labels: bug, merge

#536 YH-836: moved FormControl from UIkit
  src/features/authentication/login/ui/LoginForm/LoginForm.tsx
  src/shared/ui/FormControl/FormControl.tsx
  src/shared/ui/PasswordInput/PasswordInput.tsx
Labels: feature, merge

#551 YH-654: Added tests to Text component
  src/shared/ui/Text/ui/Text.test.tsx
Labels: merge, tests

#592 YH-826 fix aligned titles to the left
  src/shared/ui/AdditionalStatInfoGauge/ui/AdditionalStatInfoGauge/AdditionalStatInfoGauge.tsx
  src/widgets/interview/InterviewPreparation/ui/InterviewPreparation/InterviewPreparation.tsx
  src/widgets/interview/PassedQuizzesList/ui/PreviewPassedQuizzesList/PreviewPassedQuizzesList.tsx
  src/widgets/question/QuestionsList/ui/PreviewQuestionsList/PreviewQuestionsList.tsx
Labels: review, feature, merge

#586 YH-910: added filters button
  src/pages/interview/CollectionsPage/ui/CollectionsPage/CollectionsPage.module.css
  src/pages/interview/CollectionsPage/ui/CollectionsPage/CollectionsPage.tsx
Labels: bug, review, merge

#589 YH-908: Add company field to collection create/edit/view pages
  public/locales/en/collection.json
  public/locales/en/company.json
  public/locales/ru/collection.json
  public/locales/ru/company.json
  src/entities/collection/model/types/collection.ts
  src/entities/collection/ui/CollectionForm/CollectionForm.tsx
  src/entities/company/api/companyApi.ts
  src/entities/company/index.ts
  src/entities/company/model/types/company.ts
  src/entities/company/ui/CompanySelect/CompanySelect.module.css
  src/entities/company/ui/CompanySelect/CompanySelect.tsx
  src/features/collections/createCollection/model/lib/validation/collectionCreateSchema.ts
  src/features/collections/createCollection/ui/CollectionCreateFormHeader/CollectionCreateFormHeader.tsx
  src/features/collections/editCollection/model/lib/validation/collectionEditSchema.ts
  src/features/collections/editCollection/ui/CollectionEditForm/CollectionEditForm.tsx
  src/shared/assets/icons/closeCircle.svg
  src/shared/config/i18n/i18nTranslations.ts
  src/shared/ui/SelectWithChips/SelectWithChips.module.css
  src/shared/ui/SelectWithChips/SelectWithChips.tsx
  src/widgets/Collection/ui/AdditionalInfo/AdditionalInfo.module.css
  src/widgets/Collection/ui/AdditionalInfo/AdditionalInfo.tsx
Labels: review, feature, merge

#590 YH-915: add banner for new landing
  public/locales/en/landing.json
  public/locales/ru/landing.json
  src/app/providers/router/config/routeConfig.tsx
  src/app/styles/variables/button-colors.css
  src/app/styles/variables/pallete.css
  src/pages/landing/NewLandingPage/index.ts
  src/pages/landing/NewLandingPage/ui/NewLandingPage.lazy.ts
  src/pages/landing/NewLandingPage/ui/NewLandingPage.tsx
  src/shared/config/i18n/i18nTranslations.ts
  src/shared/ui/Button/Button.module.css
  src/shared/ui/Button/helpers.ts
  src/shared/ui/Button/types.ts
  src/shared/ui/Flex/Flex.module.css
  src/shared/ui/Flex/Flex.tsx
  src/widgets/NewLanding/BannerBlock/index.ts
  src/widgets/NewLanding/BannerBlock/model/assets/avatar1.avif
  src/widgets/NewLanding/BannerBlock/model/assets/avatar2.avif
  src/widgets/NewLanding/BannerBlock/model/assets/avatar3.avif
  src/widgets/NewLanding/BannerBlock/model/assets/avatar4.avif
  src/widgets/NewLanding/BannerBlock/model/assets/company.avif
  src/widgets/NewLanding/BannerBlock/model/assets/personImg.avif
  src/widgets/NewLanding/BannerBlock/model/assets/progress.avif
  src/widgets/NewLanding/BannerBlock/model/assets/statistics.avif
  src/widgets/NewLanding/BannerBlock/ui/AvatarGroup/AvatarGroup.module.css
  src/widgets/NewLanding/BannerBlock/ui/AvatarGroup/AvatarGroup.tsx
  src/widgets/NewLanding/BannerBlock/ui/BannerBlock/BannerBlock.module.css
  src/widgets/NewLanding/BannerBlock/ui/BannerBlock/BannerBlock.tsx
  src/widgets/NewLanding/BannerBlock/ui/BannerButton/BannerButton.module.css
  src/widgets/NewLanding/BannerBlock/ui/BannerButton/BannerButton.tsx
  src/widgets/NewLanding/BannerBlock/ui/BannerContent/BannerContent.module.css
  src/widgets/NewLanding/BannerBlock/ui/BannerContent/BannerContent.tsx
  src/widgets/NewLanding/BannerBlock/ui/BannerImage/BannerImage.module.css
  src/widgets/NewLanding/BannerBlock/ui/BannerImage/BannerImage.tsx
  src/widgets/NewLanding/BannerBlock/ui/BlockDescription/BlockDescription.module.css
  src/widgets/NewLanding/BannerBlock/ui/BlockDescription/BlockDescription.tsx
  src/widgets/NewLanding/BannerBlock/ui/BlockTitle/BlockTitle.module.css
  src/widgets/NewLanding/BannerBlock/ui/BlockTitle/BlockTitle.tsx
  src/widgets/NewLanding/BannerBlock/ui/Sticker/Sticker.module.css
  src/widgets/NewLanding/BannerBlock/ui/Sticker/Sticker.tsx
Labels: review, feature, merge

#594 YH-906: fix resets the question filter
  src/shared/hooks/useQueryFilter.ts
Labels: bug, review, merge

#595 YH-924: fix adding questions in collection
  src/entities/collection/ui/CollectionForm/CollectionForm.tsx
  src/entities/question/ui/ChooseQuestionsDrawer/ChooseQuestionsDrawer.tsx
  src/entities/specialization/ui/SpecializationSelect/SpecializationSelect.tsx
Labels: bug, review, merge

#596 YH-925: Fix empty collection view
  public/locales/en/questions.json
  public/locales/ru/questions.json
  src/pages/interview/CollectionPage/ui/CollectionPage.tsx
  src/shared/config/i18n/i18nTranslations.ts
  src/widgets/Collection/ui/CollectionBody/CollectionBody.module.css
  src/widgets/Collection/ui/CollectionBody/CollectionBody.tsx
  src/widgets/question/QuestionsList/ui/PreviewQuestionsList/PreviewQuestionsList.tsx
Labels: bug, review, merge

#597 YH-911: Show specialization filter only on landing
  src/widgets/Collection/ui/CollectionsFilterPanel/ui/CollectionsFilterPanel.tsx
Labels: review, feature, merge

#585 YH-903: added CompaniesTablePage into admin panel
  public/locales/en/companies.json
  public/locales/en/translation.json
  public/locales/ru/companies.json
  public/locales/ru/translation.json
  src/app/providers/router/config/routeConfig.tsx
  src/app/providers/store/config/config.ts
  src/entities/company/api/companyApi.ts
  src/entities/company/index.ts
  src/entities/company/model/constants/companyConstants.ts
  src/entities/company/model/types/companyTypes.ts
  src/entities/company/ui/CompanyCard/CompanyCard.tsx
  src/entities/company/ui/CompanyForm/CompanyForm.tsx
  src/entities/company/ui/CompanySelect/CompanySelect.tsx
  src/features/company/createCompany/model/types/companyCreateTypes.ts
  src/features/company/deleteCompanies/api/deleteCompaniesApi.ts
  src/features/company/deleteCompanies/index.ts
  src/features/company/deleteCompanies/model/constants/deleteCompaniesConstants.ts
  src/features/company/deleteCompanies/model/thunks/deleteMultipleCompaniesThunk.ts
  src/features/company/deleteCompanies/ui/DeleteCompaniesButton/DeleteCompaniesButton.tsx
  src/features/company/deleteCompany/api/deleteCompanyApi.ts
  src/features/company/deleteCompany/index.ts
  src/features/company/deleteCompany/ui/DeleteCompanyButton/DeleteCompanyButton.tsx
  src/features/company/editCompany/model/lib/validation/companyEditSchema.ts
  src/pages/admin/CollectionsPage/ui/CollectionsPage/CollectionsPage.tsx
  src/pages/admin/CompaniesTablePage/index.ts
  src/pages/admin/CompaniesTablePage/model/selectors/companiesTablePageSelectors.ts
  src/pages/admin/CompaniesTablePage/model/slices/companiesTablePageSlice.ts
  src/pages/admin/CompaniesTablePage/model/types/companiesTablePageTypes.ts
  src/pages/admin/CompaniesTablePage/ui/CompaniesTablePage/CompaniesTablePage.lazy.tsx
  src/pages/admin/CompaniesTablePage/ui/CompaniesTablePage/CompaniesTablePage.module.css
  src/pages/admin/CompaniesTablePage/ui/CompaniesTablePage/CompaniesTablePage.tsx
  src/pages/admin/CompaniesTablePage/ui/CompaniesTablePagePagination/CompaniesTablePagePagination.module.css
  src/pages/admin/CompaniesTablePage/ui/CompaniesTablePagePagination/CompaniesTablePagePagination.tsx
  src/pages/admin/CompanyDetailPage/ui/CompanyDetailPage/CompanyDetailPage.tsx
  src/shared/assets/icons/Companies.svg
  src/shared/config/i18n/i18n.ts
  src/shared/config/i18n/i18nTranslations.ts
  src/shared/config/router/routes.ts
  src/shared/config/store/State.ts
  src/shared/hooks/useQueryFilter.ts
  src/shared/types/types.ts
  src/shared/ui/EmptyStub/EmptyStub.module.css
  src/widgets/CompaniesTable/index.ts
  src/widgets/CompaniesTable/ui/CompaniesTable.module.css
  src/widgets/CompaniesTable/ui/CompaniesTable.tsx
  src/widgets/SearchSection/ui/SearchSection.tsx
Labels: review, conflicts, feature

#599 YH-930: fix PreviewCollectionsList
  src/widgets/interview/PreviewCollectionsList/ui/PreviewCollectionsList/PreviewCollectionsList.tsx
Labels: bug, review

#601 YH-923: get all questions when creating new quiz
  src/entities/quiz/api/quizApi.ts
Labels: bug, merge

#600 YH-902: Fix calendar skeleton layout
  src/shared/ui/Calendar/EventCalendar.skeleton.module.css
  src/shared/ui/Calendar/EventCalendar.skeleton.tsx
Labels: bug, review, merge
