Repository YeaHubTeam/yeahub-platform, pull requests merged in 2025-05, with the labels that each got.

#593 YH-917: add skills block
  package-lock.json
  package.json
  public/locales/en/landing.json
  public/locales/ru/landing.json
  src/app/providers/router/config/routeConfig.tsx
  src/app/styles/variables/main-variables.css
  src/pages/landing/PageTemporary/index.ts
  src/pages/landing/PageTemporary/ui/PageTemporary.lazy.ts
  src/pages/landing/PageTemporary/ui/PageTemporary.tsx
  src/shared/config/i18n/i18nTranslations.ts
  src/shared/ui/Chip/Chip.module.css
  src/shared/ui/Chip/Chip.tsx
  src/shared/ui/Chip/types.ts
  src/widgets/Landing/AboutQuestionsBlock/index.ts
  src/widgets/Landing/AboutQuestionsBlock/model/assets/androidDev.avif
  src/widgets/Landing/AboutQuestionsBlock/model/assets/dataScience.avif
  src/widgets/Landing/AboutQuestionsBlock/model/assets/docker.avif
  src/widgets/Landing/AboutQuestionsBlock/model/assets/filtersBlock.avif
  src/widgets/Landing/AboutQuestionsBlock/model/assets/frontend.avif
  src/widgets/Landing/AboutQuestionsBlock/model/assets/gameDevelopment.avif
  src/widgets/Landing/AboutQuestionsBlock/model/assets/git.avif
  src/widgets/Landing/AboutQuestionsBlock/model/assets/go.avif
  src/widgets/Landing/AboutQuestionsBlock/model/assets/html.avif
  src/widgets/Landing/AboutQuestionsBlock/model/assets/index.ts
  src/widgets/Landing/AboutQuestionsBlock/model/assets/iosDev.avif
  src/widgets/Landing/AboutQuestionsBlock/model/assets/java.avif
  src/widgets/Landing/AboutQuestionsBlock/model/assets/javascript.avif
  src/widgets/Landing/AboutQuestionsBlock/model/assets/ml.avif
  src/widgets/Landing/AboutQuestionsBlock/model/assets/postgres.avif
  src/widgets/Landing/AboutQuestionsBlock/model/assets/python.avif
  src/widgets/Landing/AboutQuestionsBlock/model/assets/react.avif
  src/widgets/Landing/AboutQuestionsBlock/model/assets/sealCheckPointer.avif
  src/widgets/Landing/AboutQuestionsBlock/model/assets/sealCheckPointerTablet.avif
  src/widgets/Landing/AboutQuestionsBlock/model/assets/swift.avif
  src/widgets/Landing/AboutQuestionsBlock/model/assets/testing.avif
  src/widgets/Landing/AboutQuestionsBlock/model/assets/typescript.avif
  src/widgets/Landing/AboutQuestionsBlock/model/assets/webpack.avif
  src/widgets/Landing/AboutQuestionsBlock/model/constants/index.ts
  src/widgets/Landing/AboutQuestionsBlock/ui/About/About.module.css
  src/widgets/Landing/AboutQuestionsBlock/ui/About/About.tsx
  src/widgets/Landing/AboutQuestionsBlock/ui/AboutQuestionsBlock/AboutQuestionsBlock.module.css
  src/widgets/Landing/AboutQuestionsBlock/ui/AboutQuestionsBlock/AboutQustionsBlock.tsx
  src/widgets/Landing/AboutQuestionsBlock/ui/Cards/CardBlockLayout/CardBlockLayout.module.css
  src/widgets/Landing/AboutQuestionsBlock/ui/Cards/CardBlockLayout/CardBlockLayout.tsx
  src/widgets/Landing/AboutQuestionsBlock/ui/Cards/CardLayout/CardLayout.module.css
  src/widgets/Landing/AboutQuestionsBlock/ui/Cards/CardLayout/CardLayout.tsx
  src/widgets/Landing/AboutQuestionsBlock/ui/Cards/FiltersCard/FiltersCard.tsx
  src/widgets/Landing/AboutQuestionsBlock/ui/Cards/SkillsCard/SkillsBlock/SkillsBlock.tsx
  src/widgets/Landing/AboutQuestionsBlock/ui/Cards/SkillsCard/SkillsCard.tsx
  src/widgets/Landing/AboutQuestionsBlock/ui/Cards/SpecializationCard/SpecializationBlock/SpecializationBlock.tsx
  src/widgets/Landing/AboutQuestionsBlock/ui/Cards/SpecializationCard/SpecializationCard.tsx
  src/widgets/Landing/AboutQuestionsBlock/ui/InterviewMaterials/InterviewMaterials.module.css
  src/widgets/Landing/AboutQuestionsBlock/ui/InterviewMaterials/InterviewMaterials.tsx
  src/widgets/Landing/AboutQuestionsBlock/ui/SkillChip/SkillChip.module.css
  src/widgets/Landing/AboutQuestionsBlock/ui/SkillChip/SkillChip.tsx
  src/widgets/Landing/AboutQuestionsBlock/ui/SkillsListTicker/SkillsListTicker.module.css
  src/widgets/Landing/AboutQuestionsBlock/ui/SkillsListTicker/SkillsListTicker.tsx
Labels: review, feature

#604 YH-929: Collections layout
  public/locales/en/collection.json
  public/locales/en/questions.json
  public/locales/ru/collection.json
  public/locales/ru/questions.json
  src/entities/collection/index.ts
  src/entities/collection/ui/CollectionPreview/CollectionPreview.module.css
  src/entities/collection/ui/CollectionPreview/CollectionPreview.sekeleton.tsx
  src/entities/collection/ui/CollectionPreview/CollectionPreview.tsx
  src/entities/question/ui/QuestionAuthor/QuestionAuthor.tsx
  src/pages/admin/CollectionPage/ui/CollectionPage.tsx
  src/pages/interview/CollectionPage/ui/CollectionPage.module.css
  src/pages/interview/CollectionPage/ui/CollectionPage.skeleton.tsx
  src/pages/interview/CollectionPage/ui/CollectionPage.tsx
  src/pages/interview/CollectionsPage/ui/CollectionsPage/CollectionsPage.module.css
  src/pages/interview/CollectionsPage/ui/CollectionsPage/CollectionsPage.skeleton.tsx
  src/pages/interview/CollectionsPage/ui/CollectionsPage/CollectionsPage.tsx
  src/shared/config/i18n/i18nTranslations.ts
  src/widgets/Collection/index.ts
  src/widgets/Collection/ui/AdditionalInfo/AdditionalInfo.module.css
  src/widgets/Collection/ui/AdditionalInfo/AdditionalInfo.skeleton.tsx
  src/widgets/Collection/ui/AdditionalInfo/AdditionalInfo.tsx
  src/widgets/Collection/ui/CollectionBody/CollectionBody.module.css
  src/widgets/Collection/ui/CollectionBody/CollectionBody.skeleton.tsx
  src/widgets/Collection/ui/CollectionBody/CollectionBody.tsx
  src/widgets/Collection/ui/CollectionHeader/CollectionHeader.module.css
  src/widgets/Collection/ui/CollectionHeader/CollectionHeader.skeleton.tsx
  src/widgets/Collection/ui/CollectionHeader/CollectionHeader.tsx
  src/widgets/Collection/ui/CollectionsFilterPanel/ui/CollectionsFilterPanel.module.css
  src/widgets/Collection/ui/CollectionsList/CollectionsList.module.css
  src/widgets/Collection/ui/CollectionsList/CollectionsList.tsx
  src/widgets/question/QuestionsList/index.ts
Labels: feature, merge

#603 YH-918: create Training block for landing
  public/locales/en/landing.json
  public/locales/ru/landing.json
  src/app/styles/variables/pallete.css
  src/app/styles/variables/themes.css
  src/shared/config/i18n/i18nTranslations.ts
  src/widgets/Landing/InterviewTrainerBlock/index.ts
  src/widgets/Landing/InterviewTrainerBlock/model/assets/quiz-image.avif
  src/widgets/Landing/InterviewTrainerBlock/model/assets/quiz-image2.avif
  src/widgets/Landing/InterviewTrainerBlock/model/assets/trainer-interview.avif
  src/widgets/Landing/InterviewTrainerBlock/ui/AdditionalBlock/AdditionalBlock.module.css
  src/widgets/Landing/InterviewTrainerBlock/ui/AdditionalBlock/AdditionalBlock.tsx
  src/widgets/Landing/InterviewTrainerBlock/ui/InterviewCard/InterviewCard.module.css
  src/widgets/Landing/InterviewTrainerBlock/ui/InterviewCard/InterviewCard.tsx
  src/widgets/Landing/InterviewTrainerBlock/ui/InterviewTrainerBlock/InterviewTrainerBlock.module.css
  src/widgets/Landing/InterviewTrainerBlock/ui/InterviewTrainerBlock/InterviewTrainerBlock.tsx
  src/widgets/Landing/InterviewTrainerBlock/ui/MainBlock/MainBlock.module.css
  src/widgets/Landing/InterviewTrainerBlock/ui/MainBlock/MainBlock.tsx
Labels: review, feature, merge

#606 YH-954: Add stub for empty collections
  public/locales/en/collection.json
  public/locales/ru/collection.json
  src/shared/ui/Card/Card.tsx
  src/widgets/interview/PreviewCollectionsList/ui/PreviewCollectionsList/PreviewCollectionsList.tsx
Labels: review, feature, merge

#608 YH-950: Fix collections list
  src/pages/interview/CollectionsPage/ui/CollectionsPage/CollectionsPage.tsx
Labels: bug, review, merge

#611 YH-958: increase collection questions limit
  src/entities/collection/api/collectionApi.ts
  src/entities/collection/model/types/collection.ts
  src/entities/collection/ui/CollectionForm/CollectionForm.tsx
  src/entities/question/ui/ChooseQuestionsDrawer/ChooseQuestionsDrawer.tsx
  src/features/collections/editCollection/ui/CollectionEditForm/CollectionEditForm.tsx
  src/pages/admin/CollectionPage/ui/CollectionPage.tsx
  src/pages/interview/CollectionPage/ui/CollectionPage.tsx
  src/shared/constants/queryConstants.ts
Labels: bug, review

#623 YH-946: Fix size of MainPage blocks in unverified profile
  src/pages/interview/MainPage/ui/MainPage.module.css
Labels: bug, review

#621 YH-964: Fix collection training questions limit
  src/features/collections/trainCollection/ui/TrainCollectionButton.tsx
Labels: bug, review

#610 YH-948: change color in chart
  src/shared/ui/charts/GaugeChart/GaugeChart.tsx
  src/shared/ui/charts/PieChart/PieSegmentList/PieSegmentList.tsx
  src/widgets/interview/QuizzesStatistic/model/getQuizQuestionsInfo.ts
  src/widgets/interview/QuizzesStatistic/ui/QuizzesStatistic/QuizzesStatistic.tsx
Labels: review, feature

#619 YH-952: Change popover to drawer in Collection
  src/pages/interview/CollectionPage/ui/CollectionPage.module.css
  src/pages/interview/CollectionPage/ui/CollectionPage.tsx
Labels: bug, merge

#624 YH-965: Remove show all categories label from quiz creating
  src/entities/question/ui/ChooseQuestionsCategories/ChooseQuestionsCategories.tsx
  src/pages/interview/CreateQuizPage/ui/CreateQuizPage.tsx
Labels: review, feature

#625 Feature/yh 916
  public/locales/en/landing.json
  public/locales/ru/landing.json
  src/shared/config/i18n/i18nTranslations.ts
  src/widgets/NewLanding/SpecialityBlock/ui/SpecializationBlock/SpecializationBlock.tsx
  src/widgets/NewLanding/SpecialityBlock/ui/SpecializationBlock/mockSpecialization.ts
  src/widgets/NewLanding/SpecialityBlock/ui/SpecializationCard/SpecializationCard.tsx
Labels: review

#626 YH-953: add icon and styles to empty questions for CollectionBody
  src/shared/assets/icons/clockSquare.svg
  src/widgets/Collection/ui/CollectionBody/CollectionBody.module.css
  src/widgets/Collection/ui/CollectionBody/CollectionBody.tsx
Labels: feature, merge

#630 YH-968: deleteв errors characters
  src/shared/ui/charts/GaugeChart/GaugeChart.tsx
Labels: bug, review

#588 YH-868: add tests for ui Input
  src/shared/ui/Input/Input.test.tsx
  src/shared/ui/Input/Input.tsx
Labels: review, tests

#614 YH-920: added History block for landing
  public/locales/en/landing.json
  public/locales/ru/landing.json
  src/app/styles/variables/pallete.css
  src/pages/landing/NewLandingPage/ui/NewLandingPage.tsx
  src/shared/config/i18n/i18nTranslations.ts
  src/widgets/NewLanding/HistoryBlock/index.ts
  src/widgets/NewLanding/HistoryBlock/model/assets/progressBarChart.avif
  src/widgets/NewLanding/HistoryBlock/model/assets/progressCircle.avif
  src/widgets/NewLanding/HistoryBlock/model/assets/progressDesc.avif
  src/widgets/NewLanding/HistoryBlock/model/assets/sealCheckPointer.avif
  src/widgets/NewLanding/HistoryBlock/model/constants/index.ts
  src/widgets/NewLanding/HistoryBlock/ui/HistoryBlock/HistoryBlock.module.css
  src/widgets/NewLanding/HistoryBlock/ui/HistoryBlock/HistoryBlock.tsx
  src/widgets/NewLanding/HistoryBlock/ui/HistorySlide/HistorySlide.module.css
  src/widgets/NewLanding/HistoryBlock/ui/HistorySlide/HistorySlide.tsx
  src/widgets/NewLanding/HistoryBlock/ui/HistorySliderBlock/HistorySliderBlock.module.css
  src/widgets/NewLanding/HistoryBlock/ui/HistorySliderBlock/HistorySliderBlock.tsx
  src/widgets/NewLanding/HistoryBlock/ui/HistoryTextBlock/HistoryTextBlock.module.css
  src/widgets/NewLanding/HistoryBlock/ui/HistoryTextBlock/HistoryTextBlock.tsx
Labels: feature, comments

#629 YH-976: fixed FiltersDrawer.tsx state and button's cursor style
  src/shared/hooks/useQueryFilter.ts
  src/shared/ui/FiltersDrawer/FiltersDrawer.module.css
  src/shared/ui/FiltersDrawer/FiltersDrawer.tsx
Labels: bug, review

#617 YH-919: Create Collections block for new Landing
  public/locales/en/landing.json
  public/locales/ru/landing.json
  src/app/providers/router/config/routeConfig.tsx
  src/entities/collection/ui/CollectionPreview/CollectionPreview.module.css
  src/entities/collection/ui/CollectionPreview/CollectionPreview.tsx
  src/shared/config/i18n/i18nTranslations.ts
  src/widgets/Landing/CollectionBlock/index.ts
  src/widgets/Landing/CollectionBlock/model/assets/miniatures/avito.avif
  src/widgets/Landing/CollectionBlock/model/assets/miniatures/index.ts
  src/widgets/Landing/CollectionBlock/model/assets/miniatures/ozon.avif
  src/widgets/Landing/CollectionBlock/model/assets/miniatures/sber.avif
  src/widgets/Landing/CollectionBlock/model/assets/miniatures/tbank.avif
  src/widgets/Landing/CollectionBlock/model/assets/miniatures/vk.avif
  src/widgets/Landing/CollectionBlock/model/assets/miniatures/wb.avif
  src/widgets/Landing/CollectionBlock/model/assets/miniatures/yandex.avif
  src/widgets/Landing/CollectionBlock/model/assets/sber.avif
  src/widgets/Landing/CollectionBlock/model/assets/tbank.avif
  src/widgets/Landing/CollectionBlock/model/assets/vk.avif
  src/widgets/Landing/CollectionBlock/model/constants/index.ts
  src/widgets/Landing/CollectionBlock/ui/AdditionalBlock/AdditionalBlock.module.css
  src/widgets/Landing/CollectionBlock/ui/AdditionalBlock/AdditionalBlock.tsx
  src/widgets/Landing/CollectionBlock/ui/CollectionBlock/CollectionBlock.module.css
  src/widgets/Landing/CollectionBlock/ui/CollectionBlock/CollectionBlock.tsx
  src/widgets/Landing/CollectionBlock/ui/FilterChip/FilterChip.module.css
  src/widgets/Landing/CollectionBlock/ui/FilterChip/FilterChip.tsx
  src/widgets/Landing/CollectionBlock/ui/FiltersBlock/FiltersBlock.module.css
  src/widgets/Landing/CollectionBlock/ui/FiltersBlock/FiltersBlock.tsx
  src/widgets/Landing/CollectionBlock/ui/MainBlock/MainBlock.module.css
  src/widgets/Landing/CollectionBlock/ui/MainBlock/MainBlock.tsx
Labels: review, feature

#636 YH-982: Dashboard account delete
  public/locales/en/profile.json
  public/locales/en/translation.json
  public/locales/en/user.json
  public/locales/ru/profile.json
  public/locales/ru/translation.json
  public/locales/ru/user.json
  src/app/styles/variables/pallete.css
  src/features/profile/deleteAccount/api/deleteAccountApi.ts
  src/features/profile/deleteAccount/index.ts
  src/features/profile/deleteAccount/model/constants.ts
  src/features/profile/deleteAccount/ui/DeleteAccountModal.module.css
  src/features/profile/deleteAccount/ui/DeleteAccountModal.tsx
  src/pages/profile/SettingsProfilePage/ui/SettingsProfilePage.tsx
  src/shared/config/i18n/i18nTranslations.ts
  src/shared/ui/Button/Button.module.css
  src/shared/ui/Modal/Modal.module.css
  src/shared/ui/Modal/Modal.tsx
  src/widgets/Profile/index.ts
  src/widgets/Profile/ui/AccountTab/index.ts
  src/widgets/Profile/ui/AccountTab/ui/AccountTab.module.css
  src/widgets/Profile/ui/AccountTab/ui/AccountTab.tsx
Labels: review, feature

#633 YH-969: Fix paddings in Table
  src/features/profile/editProfileForm/ui/EditProfileForm/EditProfileForm.module.css
  src/shared/ui/Table/Table.module.css
Labels: bug, merge

#635 YH-972: Fix missing validation messages in specialization form
  src/features/specialization/createSpecialization/model/lib/validation/specializationCreateSchema.ts
  src/features/specialization/editSpecialization/model/lib/validation/specializationEditSchema.ts
Labels: bug, merge

#634 YH-970: Fix position of pagination in admin/specializations
  src/pages/admin/SpecializationsPage/ui/SpecializationsPagePagination/SpecializationPagePagination.module.css
Labels: bug, merge

#645 YH-993: Fix public collection route
  src/entities/collection/ui/CollectionPreview/CollectionPreview.tsx
Labels: bug, review

#644 YH-992: add for Landing in landing.json en/ru translations
  public/locales/en/landing.json
  public/locales/ru/landing.json
Labels: bug, review

#638 YH-974: add Text from shared/ui for QuestionForm
  src/entities/question/ui/QuestionForm/QuestionForm.module.css
  src/entities/question/ui/QuestionForm/QuestionForm.tsx
Labels: feature, merge

#642 YH-975: change component Text
  src/entities/skill/ui/SkillForm/SkillForm.module.css
  src/entities/skill/ui/SkillForm/SkillForm.tsx
Labels: feature, comments

#647 YH-994: fix filters width
  src/pages/landing/PublicQuestionsPage/ui/PublicQuestionsPage/PublicQuestionsPage.module.css
Labels: bug, review

#652 YH-1003: fix bugs on public and interview collections pages, landing …
  src/app/providers/router/ui/AuthRoute.tsx
  src/entities/collection/index.ts
  src/entities/collection/ui/ChooseCollectionSpecialization/ChooseCollectionSpecialization.skeleton.tsx
  src/entities/collection/ui/CollectionPreview/CollectionPreview.tsx
  src/pages/interview/CollectionsPage/ui/CollectionsPage/CollectionsPage.module.css
  src/pages/interview/CollectionsPage/ui/CollectionsPage/CollectionsPage.skeleton.tsx
  src/pages/interview/CollectionsPage/ui/CollectionsPage/CollectionsPage.tsx
  src/pages/landing/PublicCollectionsPage/ui/PublicCollectionsPage.module.css
  src/pages/landing/PublicCollectionsPage/ui/PublicCollectionsPage.skeleton.tsx
  src/pages/landing/PublicCollectionsPage/ui/PublicCollectionsPage.tsx
  src/widgets/Collection/index.ts
  src/widgets/Collection/model/types/types.ts
  src/widgets/Collection/ui/CollectionsContent/CollectionsContent.module.css
  src/widgets/Collection/ui/CollectionsContent/CollectionsContent.skeleton.tsx
  src/widgets/Collection/ui/CollectionsContent/CollectionsContent.tsx
  src/widgets/Collection/ui/CollectionsFilterPanel/CollectionsFilterPanel.module.css
  src/widgets/Collection/ui/CollectionsFilterPanel/CollectionsFilterPanel.skeleton.tsx
  src/widgets/Collection/ui/CollectionsFilterPanel/CollectionsFilterPanel.tsx
  src/widgets/Collection/ui/CollectionsFilters/CollectionsFilters.module.css
  src/widgets/Collection/ui/CollectionsFilters/CollectionsFilters.skeleton.tsx
  src/widgets/Collection/ui/CollectionsFilters/CollectionsFilters.tsx
  src/widgets/Collection/ui/CollectionsFiltersDrawer/CollectionsFiltersDrawer.module.css
  src/widgets/Collection/ui/CollectionsFiltersDrawer/CollectionsFiltersDrawer.skeleton.tsx
  src/widgets/Collection/ui/CollectionsFiltersDrawer/CollectionsFiltersDrawer.tsx
  src/widgets/Landing/BannerBlock/ui/BannerButton/BannerButton.tsx
  src/widgets/Landing/JoinToCommunity/ui/JoinToCommunity/JoinToCommunity.tsx
Labels: bug, review

#655 YH-1004: Handle null createdBy in questions
  src/widgets/question/QuestionAdditionalInfo/ui/QuestionAdditionalInfo.tsx
Labels: bug, merge

#627 YH-978: fixed delete button styles in admin panel
  src/features/collections/deleteCollection/ui/deleteCollectionButton/DeleteCollectionButton.tsx
  src/features/company/deleteCompany/ui/DeleteCompanyButton/DeleteCompanyButton.tsx
  src/features/question/deleteQuestion/ui/DeleteQuestionButton/DeleteQuestionButton.tsx
  src/features/skill/deleteSkill/ui/DeleteSkillButton/DeleteSkillButton.tsx
  src/features/specialization/deleteSpecialization/ui/DeleteSpecializationButton/DeleteSpecializationButton.tsx
  src/shared/ui/Button/Button.module.css
  src/shared/ui/Button/helpers.ts
  src/shared/ui/Button/types.ts
  src/shared/ui/Popover/PopoverMenu/PopoverMenu.module.css
  src/shared/ui/Popover/PopoverMenu/PopoverMenu.tsx
Labels: bug, merge

#637 YH-977: added navigation by title text click and styles for text
  src/widgets/CollectionsTable/ui/CollectionsTable.tsx
  src/widgets/CompaniesTable/ui/CompaniesTable.tsx
  src/widgets/QuestionsTable/ui/QuestionsTable.tsx
  src/widgets/SkillsTable/ui/SkillsTable.tsx
  src/widgets/SpecializationsTable/ui/SpecializationsTable.tsx
  src/widgets/UsersTable/ui/UsersTable.tsx
Labels: bug, merge

#482 feature/YH-741
  public/locales/ru/subscription.json
  src/app/providers/router/config/routeConfig.tsx
  src/app/providers/router/ui/PremiumRoute.tsx
  src/entities/profile/index.ts
  src/entities/profile/model/selectors/profileSelectors.ts
  src/features/quiz/learnQuestion/ui/LearnQuestionButton.tsx
  src/features/quiz/resetQuestionStudyProgress/ui/ResetQuestionStudyProgressButton.tsx
  src/shared/ui/Card/ui/Card.module.css
  src/widgets/Landing/PlatformInterfaceBlock/ui/CategoriesBlock/CategoriesBlock.tsx
  src/widgets/Profile/ui/SubscriptionTab/ui/SubscriptionTab/SubscriptionTab.tsx
  src/widgets/interview/InterviewPreparation/ui/InterviewPreparation/InterviewPreparation.tsx
  src/widgets/interview/PassedQuizzesList/ui/PreviewPassedQuizzesList/PreviewPassedQuizzesList.tsx
  src/widgets/interview/QuestionsStatistic/ui/PreviewQuestionsStatistic/PreviewQuestionsStatistic.tsx
  src/widgets/question/QuestionActions/QuestionActions.tsx
  src/widgets/question/QuestionsList/ui/FullQuestionItem/FullQuestionItem.tsx
Labels: review, feature

#657 YH-1007: fix auth token update
  src/shared/config/api/baseApi.ts
Labels: bug, tests

#646 YH-979: fix search in CollectionsPage
  src/pages/admin/CollectionsPage/model/selectors/collectionsPageSelectors.ts
  src/pages/admin/CollectionsPage/model/slices/collectionsPageSlice.ts
  src/pages/admin/CollectionsPage/model/types/collectionsPageTypes.ts
  src/pages/admin/CollectionsPage/ui/CollectionsPage/CollectionsPage.tsx
Labels: bug, review

#659 YH-1006: added notifications for auth errors
  public/locales/en/translation.json
  public/locales/ru/translation.json
  src/entities/auth/api/authApi.ts
Labels: review, feature

#656 YH-941: added tests to CollectionBlock
  src/shared/ui/Button/Button.tsx
  src/shared/ui/Button/types.ts
  src/shared/ui/Card/Card.tsx
  src/widgets/Landing/CollectionBlock/model/constants/index.ts
  src/widgets/Landing/CollectionBlock/ui/AdditionalBlock/AdditionalBlock.test.tsx
  src/widgets/Landing/CollectionBlock/ui/AdditionalBlock/AdditionalBlock.tsx
  src/widgets/Landing/CollectionBlock/ui/CollectionBlock/CollectionBlock.test.tsx
  src/widgets/Landing/CollectionBlock/ui/CollectionBlock/CollectionBlock.tsx
  src/widgets/Landing/CollectionBlock/ui/FilterChip/FilterChip.test.tsx
  src/widgets/Landing/CollectionBlock/ui/FiltersBlock/FiltersBlock.test.tsx
  src/widgets/Landing/CollectionBlock/ui/FiltersBlock/FiltersBlock.tsx
  src/widgets/Landing/CollectionBlock/ui/MainBlock/MainBlock.test.tsx
  src/widgets/Landing/CollectionBlock/ui/MainBlock/MainBlock.tsx
Labels: conflicts, merge, tests

#561 YH-857: Add tests for AppLogo component
  config/jest/jest.config.ts
  src/shared/ui/AppLogo/AppLogo.test.tsx
  src/shared/ui/AppLogo/AppLogo.tsx
Labels: conflicts, comments, tests

#654 YH-980: Add tooltips to sidebar items for admin users
  src/widgets/Sidebar/ui/Sidebar/Sidebar.tsx
  src/widgets/Sidebar/ui/SidebarMenuItem/SidebarCategoryMenuItem.tsx
  src/widgets/Sidebar/ui/SidebarMenuItem/SidebarMenuItem.tsx
  src/widgets/Sidebar/ui/SidebarMenuItem/SidebarSingleMenuItem.tsx
  src/widgets/Sidebar/ui/SidebarMenuList/SidebarMenuList.tsx
Labels: review, feature
